### ISSUE TITLE
Default to whatever GitHub PR integrations are enabled, don't require a bors.toml file

### ISSUE THREAD

**Issue by frewsxcv** [bors-ng/bors-ng#101]
Speaking for myself, the only integrations I have (besides bors-ng) is Travis CI. The only status I care about is Travis. Could bors-ng just default to whatever statuses are enabled on a repository as a default and a bors.toml can be used to override that? This means that with most of my repositories, a bors.toml is not needed.

**Comment by notriddle** [comment]
Does #102 look like an acceptable way to do it? GitHub doesn't really give me a list of all integrations on a repo (doesn't help that Travis is currently a "Service," and "Services" are being deprecated). I can figure that you want to use Travis if you have a `.travis.yml` file, though.

**Comment by frewsxcv** [comment]
> Does #102 look like an acceptable way to do it?

👍 💯
