### ISSUE TITLE
Infer the use of CodeShip based on its repo config file

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#103]
According to [this](https://documentation.codeship.com/pro/getting-started/steps/), the codeship config file is one of

* jet-steps.yml
* jet-steps.json
* codeship-steps.yml
* codeship-steps.json

The "status" inference is in the "get_bors_toml.ex" file.

**Comment by notriddle** [comment]
When the `bors.toml` file is not found in the repo, a "bors.toml definition struct" is generated in the [`GetBorsToml` module](https://github.com/bors-ng/bors-ng/blob/master/apps/bors_worker/lib/batcher/get_bors_toml.ex#L17).

**Comment by notriddle** [comment]
See https://github.com/bors-ng/bors-ng/pull/183 for an example of how to do this.

**Comment by kimsaehun** [comment]
I'd like to take on this issue. 

I'm still having trouble figuring out the internals of the project so I would like to work on this for now as I explore the repo.

**Comment by kimsaehun** [comment]
I've taken a look at the "get_bors_toml.ex" file and it looks like I just have to add a {file, status} tuple for each of the files that you've mentioned. However, I'm confused as to what the value of status should be.

Looking at #183, the tuple was `{file, status} = {"circle.yml", "ci/circleci"}`. How was it determined the status identifier for the "circle" file was "ci/circleci"?
