### ISSUE TITLE
Infer the use of CircleCI based on its config file

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#104]
According to [this](http://circleci.com/docs/1.0/config-sample/), the CircleCI file is in `circle.yml`.

**Comment by roni-frantchi** [comment]
@notriddle this would surely come in handy.
Question - how do you go about setting bors with CircleCI today?
What should my `bors.toml` look like?

Thanks.

**Comment by notriddle** [comment]
Probably something like this:

```toml
statuses = ["ci/circleci"]
```

**Comment by notriddle** [comment]
When the `bors.toml` file is not found in the repo, a "bors.toml definition struct" is generated in the [`GetBorsToml` module](https://github.com/bors-ng/bors-ng/blob/master/apps/bors_worker/lib/batcher/get_bors_toml.ex#L17).
