### ISSUE TITLE
Are we allowed to modify the source code to allow private repo?

### ISSUE THREAD

**Issue by David-Vaknin-Vcita** [bors-ng/bors-ng#1070]
Hi, 
We are planning to use Bors in our private repos inside our organization.
This product is great and meets our needs; we'd like to understand if this change is allowed to fork this repo and change the code.

I really appreciate any help you can provide.

**Comment by notriddle** [comment]
Of course you can. It's licensed under the Apache-2.0 license, which permits any modification you like.

**Comment by David-Vaknin-Vcita** [comment]
Great thanks a lot for your quick response.
