### ISSUE TITLE
bors ignores all commands

### ISSUE THREAD

**Issue by RalfJung** [bors-ng/bors-ng#1098]
For some reason, bors is not reacting to commands any more in the xargo repository. Examples:
* https://github.com/japaric/xargo/pull/306
* https://github.com/japaric/xargo/pull/307
* https://github.com/japaric/xargo/pull/308

Nothing shows up in https://app.bors.tech/repositories/5730/log. One of the still-open PRs it not even listed in https://app.bors.tech/repositories/5730. Pressing the "sync" button doesn't change the situation.

Is there any way we can figure out what is happening?

Cc @japaric

**Comment by notriddle** [comment]
It looks like the installation ID changed for some reason. The old Installation ID is `88699`, while the new one is `13406157`.

I've fixed japaric's setup, so all the repos are on the new one.
