### ISSUE TITLE
Adjustable poll_period in BorsNG.Worker.Batcher

### ISSUE THREAD

**Issue by nairb774** [bors-ng/bors-ng#1143]
We run our own instance of Bors-NG (thanks!) as part of our GitOps pipeline to make sure that configs are valid before trying to deploy them. The tests are designed to run quickly (60-90s tops). Sometimes the Github webhook is missed[1], it can take a long time for Bors-NG to realize that the merge can be completed. It looks like Bors-NG has a hard-coded 30 minute backup poll here:
https://github.com/bors-ng/bors-ng/blob/00a9c17725a91ec6a22f3538c2183d43fb690200/lib/worker/batcher.ex#L41

Would it be possible to make such a value configurable for those that run the infra? Or maybe a setting that could be set for the repo? I'm not all that picky, just looking for a way to reduce the value without having to fork/build our own container - so I'm open to any suggestions.

[1] Likely related to our infra we are working to fix.

**Comment by notriddle** [comment]
> Would it be possible to make such a value configurable for those that run the infra?

Sure, that would be possible.

> Or maybe a setting that could be set for the repo?

That would also be *possible*, but I wouldn't want to allow it to go any lower than five minutes. GitHub will rate-limit us, and we don't want to risk the possibility that one project's indiscretion breaks the public instance for everyone.

**Comment by nairb774** [comment]
I would be ok with any solutions reserved to an admin. I run my own instance, with my own app. So if you only want to make it an env var/config file I'd be ok with that. I can understand the desire or need to limit this on the public version, so whatever allows you to thread that needle I would greatly appreciate.
