### ISSUE TITLE
Only use [Merged by bors] if the delete_merged_branches is on

### ISSUE THREAD

**Issue by DJMcNab** [bors-ng/bors-ng#1163]
`[Merged by Bors] -` is added to the PR title if you use a squash merge unconditionally.

https://github.com/bors-ng/bors-ng/blob/00a9c17725a91ec6a22f3538c2183d43fb690200/lib/worker/batcher.ex#L723-L729

However, this is only (usefully) read when `delete_merged_branches` is enabled and the PR is from the same repository

https://github.com/bors-ng/bors-ng/blob/f5dc2d7b5a3a1fc6cdc935898cc02309b8515ee2/lib/worker/branch_deleter.ex#L84

It would be nice to not clutter PR names with this noise when the `delete_merged_branches` setting is disabled (and for PRs not from the same repository)

@cart would like this for bevy, although it looks we will be using bors for bevy anyway.

Also the relevant documentation (at https://bors.tech/documentation/) made @cart think that the commit message would also include `[Merged by Bors] - `, which led to thinking we couldn't use bors (see https://github.com/bevyengine/bevy/issues/425#issuecomment-781755923 for in-github reference)

So it might be helpful to clarify that this doesn't affect the commits

**Comment by eric-wieser** [comment]
> However, this is only (usefully) read when `delete_merged_branches` is enabled and the PR is from the same repository

Can you elaborate on this? Do PRs from different repositories actually end up with a "merged" marker?

**Comment by DJMcNab** [comment]
So, for example, in https://github.com/bevyengine/bevy/pull/1845, bors renamed the PR to `[Merged by Bors] - ...`. However, that facility is only used by the delete source branch option.

At least the option to use a label instead might make sense.

Ideally of course, the PR could be marked as merged instead of just closed, but GitHub doesn't (seem to) allow that. 
In theory, bors could create a new branch for each PR, set the base branch of the PR to that branch, merge the PR then delete the branch, which could be a significantly nicer UX.

**Comment by eric-wieser** [comment]
> However, that is only used by the delete source branch option.

Oh, is that heading used as a marker for bors to detect dead branches? I don't understand what you mean by "used" here - I assumed that heading was purely for humans to read in the absence of github showing it as merged (#1217)

**Comment by bjorn3** [comment]
I think showing `[Merged by bors]` when using squashing is important for UX. Otherwise you would have to visit the PR to know if it was merged or not.

**Comment by cart** [comment]
Yeah I've come around on the heading. I think it's definitely useful to help indicate that the PR is merged. I'd also very much prefer that it be actually marked as purple/merged because it messes with our github statistics (and is definitely clearer for humans). But I understand that this is a github limitation 😄

**Comment by DJMcNab** [comment]
I think I'm going to close this out. My heuristic is too simplistic, and the [Merged By Bors] is useful anyways. Additionally, the issue is a suggested fix instead of a problem statement with the current state, making discussion more difficult.

As it happens, since bevy uses GitHub webhooks, this is actually better UX than merging a PR, since both merging and closing are listed as 'pull request closed' in the event title.

If anyone still wants it we can always re-open.
