### ISSUE TITLE
Make "bors cancel" an alias for "bors r-"

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#1170]
Given that "bors merge" was introduced as an alias for "bors r+", I propose making "bors cancel" be an alias for "bors r-". I've seen a lot of developers who has been confused about what "bors r+" really means, so I think "bors cancel" also will improve usability a little.

Also, don't forget to update [the documentation](https://bors.tech/documentation/) if this change is accepted.

**Comment by tharun208** [comment]
as per this pr - https://github.com/bors-ng/bors-ng/pull/746, `bors merge-` is added as another `alias` for `bors r-`.

**Comment by JensRantil** [comment]
That's nice, but I think `bors cancel` is even easier to remember and understand.
