### ISSUE TITLE
Unable to utilize GCP Health Checking

### ISSUE THREAD

**Issue by RetWolf** [bors-ng/bors-ng#1192]
Hello, I've been working on a Helm/K8S deployment for a private instance of Bors-ng and have been struggling to get load balancing working due to the fact that all the routes I've tried to health check on immediately redirect. Specifically, I'm deploying bors-ng to a Kubernetes cluster on Google Cloud Platform and their ingress controller/load balancer model automatically creates health checks that are required to pass before sending traffic to the backend service, in this case Bors. They require the health check endpoints to return 200 status codes unfortunately. I've looked into disabling the health checking or bypassing it somehow on GCP, but was unsuccessful in that approach and would prefer to have the health checks regardless.

Is there an existing route that I can use for health checking, or should I implement a simple endpoint for this case? I'm happy to do the implementation myself and make a PR for it.

**Comment by notriddle** [comment]
You should implement a simple endpoint for this case.

**Comment by RetWolf** [comment]
I've created an RFC for it here: https://forum.bors.tech/t/add-a-simple-health-check-endpoint/563 and I will begin working on a PR to implement the endpoint on my fork. Happy to adjust as needed.
