### ISSUE TITLE
Create an API

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#124]
If bors is going to switch over to [Ember.JS](https://emberjs.com/), then a prerequisite is to have an API that it can talk to. There are a number of options for how that API should work:

  * A plain REST API. This won't require any Elixir addons on top of what's already here, but every other approach listed here has an advantage over it, so probably not.
  * [JSON-API](http://jsonapi.org/) is what the Ember people seem to recommend. There's [a Plug addon for it](https://github.com/vt-elixir/ja_serializer).
  * [GraphQL](http://graphql.org) also exists. [This page explains why I think it might be better](https://jeremywsherman.com/blog/2016/07/23/why-im-meh-about-json-api/), but I'm willing to be convinced otherwise. [There is an Ember addon for it, too](https://github.com/bgentry/ember-apollo-client), and a [Plug addon](https://github.com/bgentry/ember-apollo-client), so it can be supported at both ends.

So, yeah, this is a Request For Comments.

**Comment by SirDoctors** [comment]
I agree with your thoughts for using GraphQL over JSON-API, I've had the same problems the person in that page have had and GraphQL fixes that.

**Comment by SirDoctors** [comment]
From what you have presented, it seems that you already know the answer. GraphQL does seems to be the best contender for this.

**Comment by notriddle** [comment]
The point of an RFC is that, even if the presenter thinks it's a good idea, other people might know something the presenter doesn't.

**Comment by Macarse** [comment]
what's the reasoning behind switching bors over to Ember.JS?

**Comment by notriddle** [comment]
As a reminder, EmberJS is a frontend framework, basically a UI toolkit for JavaScript running in a browser. Most of what bors does won't even be affected by the switch.

Anyway:

* People want to do a lot of data searching, sorting, and reporting in the dashboard. They want stuff like "what PRs are assigned to me and not reviewed yet" and "who reviewed the most PRs last month." It would be nice to be able to take advantage of all the nice data presentation stuff that already exists for JavaScript.

* I like having push notifications in the dashboard page. It means never having to click "Refresh." Unfortunately, the current ad hoc way it's being done is racy #79 and doesn't work very well #21.

* There are a lot more JavaScript developers than Elixir developers. You said it yourself; this is the first time you've even heard of Elixir. I'm guessing you've at l least written JavaScript at some point, however.

    I'm thoroughly convinced that Elixir/OTP is a better server framework than Node.JS, in basically every way other than raw compute performance, to the point where I'm willing to deal with it. But for UI programming, it's a completely different problem domain.

    As for why Ember in particular? [Server-side initial rendering](https://ember-fastboot.com/). I refuse to create a web application that requires you to download a bunch of JavaScript files before you can even see a data table.
