### ISSUE TITLE
bors suddenly does not react to any commands

### ISSUE THREAD

**Issue by da-kami** [bors-ng/bors-ng#1246]
At some point today bors stopped reacting to any commands on any PR in our repo https://github.com/comit-network/xmr-btc-swap/pulls

Event `bors ping` does not trigger anything. Until the latest merge into master everything worked fine.
PR where we kept trying several times today: https://github.com/comit-network/xmr-btc-swap/pull/493
(Also tried ping on other PRs and no pong received.)

Any idea what can cause this and how to fix it would be really appreciated.

**Comment by bjorn3** [comment]
Same for rust-analyzer/rust-analyzer and softdevteam/yk.
