### ISSUE TITLE
Pattern matching all github actions

### ISSUE THREAD

**Issue by hgrecco** [bors-ng/bors-ng#1300]
When using Github actions with matrix, the job name is combined with a string that describes the specifics. For example in https://github.com/hgrecco/pint-pandas the current `bors.toml` looks like this
```
status = [
  "test (3.7, numpy>=1.14,<2.0.0, pandas==1.2)",
  "test (3.8, numpy>=1.14,<2.0.0, pandas==1.2)",
  "test (3.9, numpy>=1.14,<2.0.0, pandas==1.2)",
  "lint"
]
```
But in more complex projects the numeber of `test` lines will increase. If I use `test%`, bors will be satisfied if at least 1 succeeds. Is there a way to require all status that start with `test` without individualy mame them?

**Comment by notriddle** [comment]
This normally seems to be done with a dummy job, like this one:

https://github.com/notriddle/xargo/blob/954a6cfcfeb30e8019fdf691a4687806db0bbc82/.github/workflows/ci.yml#L101

**Comment by hgrecco** [comment]
sounds good. I will give it a try
