### ISSUE TITLE
app.bors.tech is down

### ISSUE THREAD

**Issue by Undin** [bors-ng/bors-ng#1318]
https://app.bors.tech/ returns 503 currently
![image](https://user-images.githubusercontent.com/2539310/133157640-02693b4e-1a20-4e7a-bc5b-a935a78867ef.png)

As a result, the corresponding pull requests cannot be merge

**Comment by notriddle** [comment]
I see. It's back up now. Sorry about this.

**Comment by Undin** [comment]
@notriddle Thank you!
