### ISSUE TITLE
Fail because of status required by GitHub (Milestone Check)

### ISSUE THREAD

**Issue by curquiza** [bors-ng/bors-ng#1357]
Hello,

Sorry if it's not the right place to write my issue

We are using bors in several repositories. One of these repositories requires a milestone to be set in order to merge a PR.
We added the [PR Milestone Check](https://github.com/scholzj/milestone-check) integration to our repo.

We added this check status as mandatory to merge a PR, cf our settings for the `main` branch

<img width="919" alt="Capture d’écran 2021-10-13 à 14 37 01" src="https://user-images.githubusercontent.com/20380692/137133656-0feb15f0-6f5d-41ac-9fae-db88567e2968.png">

Here is our `bors.toml`: https://github.com/meilisearch/MeiliSearch/blob/main/bors.toml

It's logical bors does not succeed to merge if the milestone is missing in the GitHub PR. However, for multiple PRs, it happened bors did not succeed to merge, for the reason of this missing status (Milestone Check), according to the error message, but the milestone is well added to the PR

See this PR: https://github.com/meilisearch/MeiliSearch/pull/1803

Thanks for your work, despite this, we love using bors every day, it saves us so much time 🙏

**Comment by curquiza** [comment]
Is it normal we already succeeded to merge dozen and dozen of PRs without putting the Milestone Check on our bors.toml file?

**Comment by curquiza** [comment]
> Yeah, it means that you've been merging them one at a time. This only becomes a problem when you have batches with multiple PRs in them at once.

No, we did not merge multiple PRs at the same time. We try one by one but we still had the issue.

**Comment by notriddle** [comment]
If it needs to be run on the PR, and not on the final merge commit, then use the `pr-status = "Milestone Check"` config option instead.

**Comment by curquiza** [comment]
I think we succeeded to remove the problem with `pr-status`, thanks @notriddle!
I close the issue
