### ISSUE TITLE
Add configurability to branch names

### ISSUE THREAD

**Issue by Xavientois** [bors-ng/bors-ng#1404]
It would be useful to be able to change the names of the `trying` and `staging` branches to something else in order to not conflict with existing names.

I see from [this line](https://github.com/bors-ng/bors-ng/blob/a1b31786d48839f67fd5691564217e8538f74b24/lib/database/project.ex#L42) that these names are not hard-coded, so it looks like it might be a matter of exposing those two parameters through the config file. I am not very familiar with Elixir, though, so I might be mistaken in this regard.

**Comment by notriddle** [comment]
You can change the name of those branches from the dashboard. It’s in the same place that you configure permissions:

https://forum.bors.tech/t/adding-new-reviewers-to-a-repository/73

**Comment by Xavientois** [comment]
Thank you! That is exactly what I was looking for.
