### ISSUE TITLE
Permissions synchronize update fails

### ISSUE THREAD

**Issue by vladmalynych** [bors-ng/bors-ng#1441]
We are using private repo, and self hosted bors-ng.

When trying to synchronize permissions
<img width="1028" alt="Screenshot 2022-01-25 at 23 57 29" src="https://user-images.githubusercontent.com/17581967/151073735-e51679e6-7cf1-4c58-adea-89082dec0057.png">

It fails on timeout:
```
17:38:34.339 pid=<0.2260.0> [error] Task #PID<0.2260.0> started from #PID<0.2252.0> terminating
** (stop) exited in: GenServer.call(BorsNG.GitHub, {:get_open_prs, {{:installation, 10222601}, 10935048}, {}}, 100000)
    ** (EXIT) time out
    (elixir 1.12.0) lib/gen_server.ex:1024: GenServer.call/3
    (bors 0.1.0) lib/github/github.ex:113: BorsNG.GitHub.get_open_prs!/1
    (bors 0.1.0) lib/worker/syncer.ex:37: BorsNG.Worker.Syncer.synchronize_project/1
    (elixir 1.12.0) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<0.67999664/0 in BorsNG.Worker.Syncer.start_synchronize_project/1>
    Args: []
```

We have 300+ open PRs and github is not able to finish request in 100 sec. 

[Increasing this hardcoded value](https://github.com/bors-ng/bors-ng/blob/b70bb2504d0afb76e402866ec3c8c92ad0de3730/lib/github/github.ex#L116), and building a new image helped.
Proposed changes: use env variable for get_open_prs timeout.

**Comment by notriddle** [comment]
Does the PR you made, referencing this issue, actually fix it?

**Comment by vladmalynych** [comment]
Hi, yes with this changes I am able to increase timeout for `get_open_prs` by defining `GITHUB_API_TIMEOUT` env.
I just start a container with env `GITHUB_API_TIMEOUT: '200000'`, this resolved my issue.

**Comment by notriddle** [comment]
Cool. Thanks!
