### ISSUE TITLE
Have the PR title appear in the merge commit subject. Is it possible?

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [bors-ng/bors-ng#1457]
Hello,
I've been digging through the source code and I think the answer is **no**.

Is it possible to use the PR title as the subject of the merge commit?

If not, is this a feature that could be implemented or is it undoable with the current design of the software? (I was going to try and submit a PR)

**Comment by notriddle** [comment]
It's not a currently-present feature.

The problem with doing it is batching; if you have five different PRs merged with the same merge commit, do all of their messages go on one line? Or does one of them get to be the title, while the others all get pushed down in the message?

**Comment by Fire-Dragon-DoL** [comment]
> It's not a currently-present feature.
> 
> The problem with doing it is batching; if you have five different PRs merged with the same merge commit, do all of their messages go on one line? Or does one of them get to be the title, while the others all get pushed down in the message?

Thank you, that's what I wanted to discuss/understand. The problem would indeed be batching and I have no solution for that. In my mind each PR would be its own merge commit, but from my understanding this is not possible.

It doesn't make sense in the other cases, all titles on the subject would be very long and there is no way to determine (if only one was going to be used) which one would be at the top.

Thanks for the details, I think we can close, I can't figure out a solution to this problem in a way that does make sense.
