### ISSUE TITLE
Heroku deploy does not work

### ISSUE THREAD

**Issue by nykolaslima** [bors-ng/bors-ng#1494]
I have configured the Github App and when deploying the Heroku app I got an error:
```
Configure environment
There was an issue setting up your app environment.

Service temporarily unavailable. Please try again later.
```
![image](https://user-images.githubusercontent.com/1128572/164794326-33abff8c-ae59-427c-8733-bab719144ec1.png)

Any ideas on what should be wrong?

**Comment by Jroze88** [comment]
Heroku has temporarily disabled linking github, try the CLI?

[install for your os](https://devcenter.heroku.com/articles/heroku-cli)
then from the root of your git repository:
`heroku login` 
`heroku git:remote -a your-app-name-on-heroku`
`git remote -v` you should see (push) and (fetch) messages between your heroku app and the github project
`git push heroku main` or whichever branch you deploy

It should show you the heroku build logs in the terminal as it deploys

**Comment by nykolaslima** [comment]
Hi @Jroze88 looks like the Heroku's addons are down:
```
➜  workspace heroku addons:create heroku-postgresql:hobby-dev -a bors-merce
Creating heroku-postgresql:hobby-dev on ⬢ bors-merce... !
 ▸    Service temporarily unavailable. Please try again later.
```

**Comment by notriddle** [comment]
This is interesting, but it's definitely Not My Problem.

If you're looking for a workaround, consider a [docker-based deployment instead](https://forum.bors.tech/t/setting-up-bors-with-docker-compose/205).
