### ISSUE TITLE
Question: Anyway to make bors the only one who can push to a protected branch?

### ISSUE THREAD

**Issue by roni-frantchi** [bors-ng/bors-ng#156]
How would I go about and make sure that no dev really pushes to `master`, but rather `bors r+` his way there?

Since `bors` shows up as an integration rather than a user, I can't add GitHub's list of permitted committers.

**Comment by notriddle** [comment]
You can use GitHub's ability to block based on a Commit Status. That's what I do.

**Comment by roni-frantchi** [comment]
Right. That'll do it. Thanks.
