### ISSUE TITLE
bors crashing with "head does not exist" error

### ISSUE THREAD

**Issue by bryangingechen** [bors-ng/bors-ng#1578]
We're trying to merge https://github.com/leanprover-community/mathlib4/pull/838 with bors, but it has been crashing all day with more or less the same message:

```elixir
{{:badmatch,
  {:error, :merge_branch, 404,
   "{\"message\":\"Head does not exist\",\"documentation_url\":\"https://docs.github.com/rest/branches/branches#merge-a-branch\"}",
   "D47C:4107:24613B9:4AF69FA:638BB069"}},
 [
   {BorsNG.GitHub, :merge_branch!, 2,
    [file: 'lib/github/github.ex', line: 185]},
   {Enum, :"-reduce/3-lists^foldl/2-0-", 3,
    [file: 'lib/enum.ex', line: 2468]},
   {BorsNG.Worker.Batcher, :start_waiting_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 442]},
   {BorsNG.Worker.Batcher, :poll_, 1,
    [file: 'lib/worker/batcher.ex', line: 297]},
   {BorsNG.Worker.Batcher, :handle_info, 2,
    [file: 'lib/worker/batcher.ex', line: 237]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 1123]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 1200]},
   {:proc_lib, :init_p_do_apply, 3,
    [file: 'proc_lib.erl', line: 240]}
 ]}
```

(Our bors log is here: https://app.bors.tech/repositories/37904/log )

Is there something we need to fix with the PR?

**Comment by alreadydone** [comment]
> (Our bors log is here: [app.bors.tech/repositories/37904/log](https://app.bors.tech/repositories/37904/log) )

I can't view the log (permission denied); maybe you can paste it as a gist or a text file?

**Comment by bryangingechen** [comment]
I posted the crash message for the latest crash above; the others are mostly the same.

**Comment by bryangingechen** [comment]
bors seems to have started working again after we merged the affected PRs by hand. Closing for now.
