### ISSUE TITLE
PR stuck in "waiting in queue" state

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#158]
Hi! Looks like something's wrong with https://github.com/intellij-rust/intellij-rust/pull/1139.

Status says "bors — Waiting in queue", but no travis builds are in progress.

**Comment by notriddle** [comment]
[According to the queue viewer, it's not waiting in the queue any more.](https://bors-app.herokuapp.com/repositories/81)

**Comment by matklad** [comment]
But it definitely says "waiting in queue" in the PR UI though:

![queue](https://cloud.githubusercontent.com/assets/1711539/25056718/5c696d2c-2173-11e7-88c2-e7644f50546b.png)

It doesn't seem to be a client caching issue: reloaded the page several times with caching disabled.
