### ISSUE TITLE
Visited links look surprisingly on the dashboard

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#159]
Hi! Currently, links in the dashboard use custom colors for visited/not visited states:

![links](https://cloud.githubusercontent.com/assets/1711539/25056517/1430297a-2172-11e7-96ba-80214533b3ba.png)

This is a bit confusing because the difference in color is really pronounced and looks like an indication of the failure/success status because of the reddish tint of the visited link. Perhaps visited/not visited colors should not differ that much in general? Alternatively, it may be worthwhile to remove the "visited" marker from these particular links altogether, it does not seem to add much value, but does add some noise.

**Comment by notriddle** [comment]
Good point.

**Comment by notriddle** [comment]
The color is specified [in app.css](https://github.com/bors-ng/bors-ng/blob/54d39a2a0b1c2713507d57d0daadfb7d8aff08c2/apps/bors_frontend/web/static/css/app.css#L79)
