### ISSUE TITLE
Status of `staging` and `trying` not being reported back as `borg` status

### ISSUE THREAD

**Issue by roni-frantchi** [bors-ng/bors-ng#166]
After `bors r+`ing or `bors try`ing, bors successfully branches off `staging`/`trying` and merges `master` into it.
Jenkins then kicks in a build for the `staging`/`trying` branch, and reports its commit status back to GitHub - e.g., when navigating to `github.com/org/repo/branches/staging/commits/` you can see the status of the build being reported back by Jenkins.
The `borg` required status on the Pull Request however, is still being shown as `Running`.
I'm not seeing any errors on the Heroku logs, nor do I see any failed request on the integration I set up...

Any ideas?..

**Comment by roni-frantchi** [comment]
got this off the logs:
```2017-04-16T14:05:03.946153+00:00 app[web.1]: ** (exit) an exception was raised:
2017-04-16T14:05:03.946154+00:00 app[web.1]:     ** (MatchError) no match of right hand side value: {:error, :get_pr, 401, 1250}
2017-04-16T14:05:03.946155+00:00 app[web.1]:         (bors_github) lib/github.ex:27: BorsNG.GitHub.get_pr!/2
2017-04-16T14:05:03.946155+00:00 app[web.1]:         (bors_frontend) web/command.ex:65: BorsNG.Command.fetch_pr/1
2017-04-16T14:05:03.946156+00:00 app[web.1]:         (bors_frontend) web/command.ex:199: BorsNG.Command.run/3
2017-04-16T14:05:03.946157+00:00 app[web.1]:         (bors_frontend) web/controllers/webhook_controller.ex:82: BorsNG.WebhookController.webhook/2
2017-04-16T14:05:03.946157+00:00 app[web.1]:         (bors_frontend) web/controllers/webhook_controller.ex:1: BorsNG.WebhookController.action/2
2017-04-16T14:05:03.946158+00:00 app[web.1]:         (bors_frontend) web/controllers/webhook_controller.ex:1: BorsNG.WebhookController.phoenix_controller_pipeline/2```

**Comment by notriddle** [comment]
That error was fixed in a recent commit. You might want to upgrade.

**Comment by notriddle** [comment]
Did bors get around to moving staging into master after Jenkins reported its success? Or did bors just completely ignore Jenkins's report entirely?

**Comment by roni-frantchi** [comment]
> That error was fixed in a recent commit. You might want to upgrade.

Upgrading did get rid of the error.

> Did bors get around to moving staging into master after Jenkins reported its success?

Not it did not. It seems like bors just completely ignores Jenkins report.
It does change its status from `Waiting in queue` to `running` as soon as Jenkins starts to build.
But when Jenkins finishes, and the status is shown on the `staging` branch commit, the PR remains with the same `running` status for bors.

**Comment by notriddle** [comment]
In the bors.toml file, you need to specify a "context" that bors should look for. What context is specified in there? Is it *exactly* the same one that Jenkins is using?

**Comment by roni-frantchi** [comment]
@notriddle that's interesting - 
Jenkins reports back the PR status as `continuous-integration/jenkins/pr-head`, which is what I set in in my `bors.toml`.
However, I believe it that for **branches** (with no PRs - like `trying`, `staging`) it reports the statuses with a different name (probably not `pr-head`, as it insinuates PR).
I'll try and figure out if that's the case.
If so, which of the statuses am I to put in as context?.. both? how do i do that?

**Comment by notriddle** [comment]
Use continuous-integration/jenkins/branch

**Comment by notriddle** [comment]
Do not include the pr-head one in the context list.

**Comment by roni-frantchi** [comment]
OK so setting the context to `continuous-integration/jenkins/branch` seems to have worked - bors no longer times out.
However, now once the build finishes successfully, bors immediately Cancels, and the status is reported as "canceled".
I can't see anything of value in the logs (though I can post them here).
But I have a theory that maybe bors tries to merge the PR to `master` but fails due to some validation I still have from my protected branch.
It would be either that the PR branch is out of date compared to the master (not sure how to disable this validation.. as it probably is no longer needed with bors), or the fact that the PR needs to be approved by someone. Which I can disable if I make it so that bors is required.

Any thoughts?

**Comment by notriddle** [comment]
![Turn off "Require branches to be up do date before merging"](https://cloud.githubusercontent.com/assets/1593513/25203837/a79731ea-250f-11e7-8fd8-937d36055a39.png)

**Comment by roni-frantchi** [comment]
OK so the issue was I had the "Require pull request reviews before merging" turned on.

Now, one might claim it can be turned off when using bors as if someone "bors r+" you're fine.
But that's not always the case. If someone had used GitHub reviews to request changes, only the one who had made the request may approve (or dismiss) the review. And so the review must be accounted for.

And so I was thinking I should keep it, and benefit from both.
The downside is that in case someone tries to `bors r+`, I feel like instead of attempting the build and then failing on a generic "bors canceled" message, a more descriptive reason as to why the branch couldn't be merged like "Can't merge a branch with requested changes pending" could be posted right away.
What do you think @notriddle ?

**Comment by notriddle** [comment]
It would basically be like #24 and #50, except for Reviews instead of Labels or Statuses.

**Comment by notriddle** [comment]
Also, [anyone with write access to a repo can dismiss a review](https://help.github.com/articles/dismissing-a-pull-request-review/).

**Comment by roni-frantchi** [comment]
> Also, anyone with write access to a repo can dismiss a review.

They have recently changed that - [You can restrict review dismissals with protected branches.](https://github.com/blog/2330-restrict-review-dismissals-with-protected-branches)

**Comment by notriddle** [comment]
I see. Thanks!
