### ISSUE TITLE
Add a way to block on GitHub reviews

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#168]
Another pre-check before running the test suite (like #112 and #50), but this time based on GitHub Pull Request Reviews.

Mentioned in #166.

**Comment by couchand** [comment]
Was this closed by #362?

**Comment by JensRantil** [comment]
Is https://github.com/bors-ng/bors-ng/issues/375 related?

**Comment by notriddle** [comment]
Yes, it should be closed. My mistake.
