### ISSUE TITLE
🔒 Permission denied ?

### ISSUE THREAD

**Issue by roni-frantchi** [bors-ng/bors-ng#169]
Had one of my team members who has full repo access try and `bors r+`, but bors says: 🔒Permission denied.

Why is that?..

**Comment by roni-frantchi** [comment]
I think it might be because I did `bors r-` at some point...
But I'm not sure. The response just says "Permission Denied" with no reason provided.

Is my own `bors r-` the reason? 
Does that mean I'm the only one who can `bors r+` it back? Can an admin override it?
Is there a way to cancel the build without `bors r-`? 
Is there a wiki around which other `bors ` commands can be used and how?

**Comment by matklad** [comment]
@roni-frantchi I think the list of reviewers is controlled via dashboard and **is not** populated from repository collaborators automatically. 

Link to the dashboard: https://bors-app.herokuapp.com/

**Comment by roni-frantchi** [comment]
Thanks @matklad.
I'm using a bors instance [deployed to my own dyno](https://github.com/bors-ng/bors-ng#how-to-set-up-your-own-real-instance). 
When navigating to the dashboard of my own instance I'm able to see just a list of the organization repository. Where should I be looking for the list of reviewers?

Also worth mentioning, it seems like `bors r-` wasn't the issue. Whenever any of my teammates try to approve they face `Permission denied`.
Oh and when they login to the dashboard, they don't see anything under "Awaiting review"...

**Comment by matklad** [comment]
>Where should I be looking for the list of reviewers?

If you click a particular repository on the dashboard, you'll see a list of reviewers in the settings tab:

![r](https://cloud.githubusercontent.com/assets/1711539/25232232/44e6e50c-25e3-11e7-83bd-8025378452de.png)

**Comment by roni-frantchi** [comment]
That did it! 🎉 Thanks @matklad 

> I think the list of reviewers ... is not populated from repository collaborators automatically

That's unfortunate. We're a team of 15 strong and growing... Going to somewhat of a hassle to maintain

**Comment by roni-frantchi** [comment]
@notriddle any thoughts on permitting reviewers based on the repo collaborators?

**Comment by notriddle** [comment]
This is definitely something that bors should support.

**Comment by notriddle** [comment]
See: #90 and #165

**Comment by roni-frantchi** [comment]
Cool. Thanks!
