### ISSUE TITLE
Option to delete branch automatically once it has been merged

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#177]
Feature request. 

Using bors-ng workflow results in tons of merged branches. It would be convenient if bors automatically deleted remote branch after it had been merged.

**Comment by Macarse** [comment]
@notriddle I noticed you do this with your prs. You do it yourself through the cmd line, right?

**Comment by notriddle** [comment]
I use the CLI to open Pull Requests, and you can delete a branch using the CLI with `git push origin :BRANCH_NAME`, but that's not the point.

The point is that you don't need a branch after it's merged, so bors should just delete it.

**Comment by Macarse** [comment]
@notriddle oh, yes, it totally makes sense to me but  I wanted to understand how it was happening now.

PS: you can also use `git push --delete origin branch_name` which is the "new" way :)

**Comment by notriddle** [comment]
Fixed by #237
