### ISSUE TITLE
Synchronize pull requests

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#18]
Code needs to be implemented that fetches a list of open pull request from GitHub. Using this list, the code should do this:

 1. For every open pull request that GitHub returns, if there is no corresponding patch in bors's database, create the patch.
 2. For every patch that was not processed as part of step 1, mark it as closed.

This code should run when a repository is added, so that people can immediately start reviewing pull requests that existed before bors was added. In this case, step 2 shouldn't do anything.

A button to do this should also be added to the repository dashboard. This is a workaround in case a webhook is dropped. Unlike homu, this button should not also poll the batches, because we already do that on an automatic schedule.

The synchronization should ideally be done in a background process, because it's going to take awhile, and the UI can be kept up-to-date with a Phoenix channel. The initial implementation doesn't need to do this, but it should be structured in a way that doing so is feasible.

**Comment by TheDoctorsLife** [comment]
This is closed as of https://github.com/bors-ng/bors-ng/pull/77
