### ISSUE TITLE
Take advantage of pull request status information when available

### ISSUE THREAD

**Issue by mmun** [bors-ng/bors-ng#185]
Consider the situation where:

- Pull requests are built the same way as staging/trying.
- The tests pass on a pull request.
- The pull request has master as an ancestor.
- There is nothing else in bors' merge queue.

In this case, if someone writes "bors r+" it would be logically possible to skip running the tests a second time because that wouldn't give you any new information. We already know this commit passes.

This situation isn't too uncommon, e.g. merging a small fix after you merge a feature branch.

This feature would rely on pull requests and staging/trying being tested in the same way. For this reason, it might make sense to make this behaviour opt-in to avoid confusion.

**Comment by kamalmarhubi** [comment]
You could even go a step further: use the tree sha. If someone just edits the commit message and force pushes, there's no reason to require another build.
