### ISSUE TITLE
Include pull request author in the merge commit message

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#186]
Currently merge commit message looks like this:

```
Merge #1186  …
1186: local variable documentation r=matklad
Add quick documentation for local variables.
bors[bot] committed 12 days ago 
```

It would be useful to have `author=JohnDoe` in addition to `r=matklad`.

**Comment by notriddle** [comment]
Fortunately, the patches schema [already contains the author](https://github.com/bors-ng/bors-ng/blob/master/apps/bors_database/lib/patch.ex#L22). It's just not included in the [commit message](https://github.com/bors-ng/bors-ng/blob/master/apps/bors_worker/lib/batcher/message.ex#L74).

For this to work right, though, you're also going to need to load the author information in the database. The [preload](https://hexdocs.pm/ecto/Ecto.Repo.html#c:preload/3) function is how you populate these kinds of "gaps" in Ecto.
