### ISSUE TITLE
Switch the webhook controller from Integration events to App events

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#189]
According to GitHub's recent [blog post](https://developer.github.com/changes/2017-05-22-github-apps-production-ship/):

> With the name change to GitHub Apps, there are some changes to webhook events, payloads and API responses.
>
> The `integration_installation` and `integration_installation_repositories` event names, used in the Early Access period, have been deprecated in favor of `installation` and `installation_repositories`. All GitHub Apps receive these events to their webhook by default, so all applications are affected by this change.

The code to handle these events is in the [`BorsNG.WebhookController`](https://github.com/bors-ng/bors-ng/blob/72e27c02dffa0698785c97645e3999b0772c526f/apps/bors_frontend/web/controllers/webhook_controller.ex#L93) module. The events are not semantically different; you just need to change the name. It helps that we never used the `integration_id` anyway; we only use the `installation_id`, which has not been renamed.

You'll also need to fix the doctest at the top of the file.

**Comment by jniles** [comment]
I've never programmed erlang before, but would love to learn.  This issue seems like a good place to start since it involves getting the development environment set up without risking committing first-time-mistakes.  :)

Mind if I update the tests and documentation something this next week?

**Comment by notriddle** [comment]
Good luck!

**Comment by notriddle** [comment]
How's it going? Need any help?

**Comment by jniles** [comment]
Ah, my schedule ran out of time and I've been prepping for international travel.  Today I fly back to the continental US and that should give me breathing room to take a strong wack at this.

**Comment by notriddle** [comment]
@jniles Should I remove your C-assigned marker from this PR?

**Comment by jniles** [comment]
@notriddle yeah, let's open up to anyone.

**Comment by leeopop** [comment]
Hi,
It's 2020 but I still have deprecated events from github.

![image](https://user-images.githubusercontent.com/3205589/79188977-8400f380-7e5b-11ea-97eb-fda1d0ffd4b1.png)

Why don't we provide renaming hooks for them?


I'm newbie to elixer, however adding renaming functions to `webhook_controller` did work for me.

```
  def do_webhook(conn, "github", "integration_installation") do
    do_webhook conn, "github", "installation"
    conn
    |> send_resp(200, "")
  end

  def do_webhook(conn, "github", "integration_installation_repositories") do
    do_webhook conn, "github", "installation_repositories"
    conn
    |> send_resp(200, "")
  end
```
