### ISSUE TITLE
Wrong "not awaiting review" comment

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#196]
For the PR i've r+'ed, bors replied that it does not await a review, although it was the only r+ on this PR:

https://github.com/intellij-rust/intellij-rust/pull/1282#issuecomment-304500234

**Comment by notriddle** [comment]
Did you edit the comment?

**Comment by matklad** [comment]
Yeah, the UI says "edited", so I must have fixed a typo somewhere.

**Comment by notriddle** [comment]
Okay, yeah, I know what the bug is, then.
