### ISSUE TITLE
Priority

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#201]
* Make sure that every PR in a batch has the same priority. This is the same way bors-ng does multiple branches.

* Pick PRs with a higher priority over ones with a lower priority. That's an ORDER BY clause.

* When a PR gets added, if the current running batch has a lower priority than the new PR, cancel the current batch and put the batch's PRs back into the queue.

CC https://github.com/servo/homu/issues/102

**Comment by khodzha** [comment]
id like to work on this, can you elaborate on how we should set priorities in the first place?

**Comment by notriddle** [comment]
If you want to copy the homu syntax, then you would add a command with this syntax:

    bors p=<positive-or-negative-integer>

This sets a column in the `patches` table, which gets carried forward to the batch.

However, homu also allows syntax like these:

> bors r+ p=10



> bors p=10
>
> Once we r+ it, it'll go in front.

Both of these will be interpreted as *set the priority to 10, then put it in the queue*. I think we want to support the first one, but not the second one.

So I guess there's two ways to set a priority:

* The `p=` command
* The `p=` parameter to the `r+` and `r=` commands.

**Comment by notriddle** [comment]
This sound good to you, @Macarse?

**Comment by notriddle** [comment]
Welp, it's been ten days. If we implement this and @Macarse complains then that's his problem.
