### ISSUE TITLE
Add a configuration option for batch size limiting

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#205]
There are really two possible ways that you want to limit the size of a batch:

* Patch-specific limits. This would be used by servo/servo (that need to sync up with a worlds-apart Mercurial repo).
* Repo-wide limits. rust-lang/rust would want this for their bisect process, and @mmun would want it since their company doesn't want batching at all.

**Comment by kimsaehun** [comment]
I'd like to use this issue as a way for me to explore the backend of BorsNG. Could I have this assigned to me please?

**Comment by kimsaehun** [comment]
Hi, I haven't had much time to work on this and I will be busy for the next 2-3 weeks so that will explain my inactivity. I'll post an update if I am still busy afterwards but if not, I will come back to work on this.

**Comment by kimsaehun** [comment]
Could you explain how the patch-specific limits would work please?

By Repo-wide limits, I'm thinking that each repo will be able to be configured to have batches be limited to X number of patches. However, I'm not quite sure how a patch-specific limit would work.

**Comment by notriddle** [comment]
The simplest way to do it would be to add a way to prevent a particular patch from ever being placed into a batch. For example, you could do `bors r+ single`, and from then on the patch would always run alone. It would involve adding a new column to the `patches` table to include this marker.

**Comment by kimsaehun** [comment]
Thanks for the clarification. I'll try implementing the `bors r+ single` command.

**Comment by kimsaehun** [comment]
Would the `single` command make more sense as a one time execution rather than a persistent execution?

I'm thinking of a case where one does a  `bors r+ single`, tests fail, and then does a `bors r+` because the second time around the user isn't concerned with whether the patch is batched or not. So the user would have to do the `single` command each time they want it to be isolated.

**Comment by notriddle** [comment]
We have to track it in the database anyway, because there might be something in front of it in the queue, so we need to be able to enqueue it without batching it.

The reason I figured it should be a flag is that, in the case where the first `bors r+ single` and the second go-around is `bors r+`, it seems equally likely that the user may or may not intend it to run single the second time. It might be the case that this patch ought never to be batched (that's what Servo would have wanted). It might instead be the case that it was only the first run that needed to be single. Both scenarios make sense, so just go with whichever one is easier to implement.
