### ISSUE TITLE
Allow bors.toml to be stored in the .github folder

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#212]
This is supported by a lot of other GitHub Apps, like [probot] (and the built-in stuff that GitHub uses). It allows people to keep the top level of their project cleaner.

The logic for finding or generating the bors.toml file is in [bors-ng/apps/bors_worker/lib/batcher/get_bors_toml.ex].

[probot]: https://github.com/probot
[bors-ng/apps/bors_worker/lib/batcher/get_bors_toml.ex]: https://github.com/bors-ng/bors-ng/blob/471c98fb5ac7c697b254e1eca3e0aefa353179db/apps/bors_worker/lib/batcher/get_bors_toml.ex

**Comment by mmun** [comment]
I like this :+1:
