### ISSUE TITLE
Show a "nothing to see here" placeholder on the patch list for projects that have no open patches

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#22]
Exactly what it sounds like. You should say that there are no open pull requests, instead of just not showing anything.

**Comment by notriddle** [comment]
It's in [project/index.html.eex](https://github.com/bors-ng/bors-ng/blob/master/apps/bors_frontend/web/templates/project/index.html.eex).

**Comment by abeltensor** [comment]
I have a solution if you are interested.  

I implemented two helper functions into the project_view.eex folder to check if the projects list is empty. Then I added a few lines into the index.eex file which uses these new functions to show the table or show the "nothing to see here" placeholder.  Its a fairly basic solution but I figured you would want to build on it from there. 

heres what index would look like:

`<nav><div class=wrapper>
<h1>Repositories</h1>
</div></nav>

<main role=main><div class=wrapper>

<div class=toolbar>
  <a class=toolbar-item href="<%= BorsNG.Attrs.get_github_integration_url() %>">
    Add / Remove Repositories
  </a>
</div>
<%= if empty? @projects do %>
  Nothing to See here!
  <% else %>

<table class="table">
  <tbody>
<%= for project <- @projects do %>
    <tr role=row>
      <td class="fill-link">
        <%= link project.name, to: project_path(@conn, :show, project) %>
      </td>
    </tr>
<% end %>
<% end %>
  </tbody>
</table>

</div></main>`

Here are the empty? helper functions:
`def empty?([]), do: true
  def empty?(list) when is_list(list) do
    false
  end
`

**Comment by notriddle** [comment]
Is there some reason you didn't just use `if @projects == []`?

And, yes, I'm interested! Thanks for working on this :+1:

**Comment by abeltensor** [comment]
I used the helper functions because it just seemed like a more elegant solution then hard coding the conditional.  Obviously either or still works however.

**Comment by notriddle** [comment]
That makes sense, let's go with that then.

**Comment by abeltensor** [comment]
No problem, shall I make a pull request then?

**Comment by notriddle** [comment]
Yep. :octocat:
