### ISSUE TITLE
Should we adopt a standard commit message style?

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#230]
Right now, I've been using the [Linux-style commit messages](https://chris.beams.io/posts/git-commit/). Other contributors have used [Angular-style commit messages](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit?pref=2&pli=1). Others have used simpler choices, like just writing sentences.

If a standard is going to be adopted, the Angular one would probably be more worthwhile, since it's easier to parse and thus build tooling around. @jniles has been using it, so could probably say more about it.

OTOH, the to-be-parsed-metadata doesn't need to all be in the title. I know Rust and GitHub itself put markers in the body of the commit messages.

**Comment by jniles** [comment]
At this point, unless there is a strong reason for the standard message styling, I would advise against it.  I think the lack of a standard commit style works in bors-ng's favor and helps onboard contributors.

In my mind, a strict commit message syntax is most beneficial to projects that want rapid, concise, and correct changelogs/history files.The auto-parsing is not very useful if it is not enforced, and the major downside is that they make the contribution process one more step harder by asking the contributor to learn and conform to that syntax.  In the best case, it's a bit of a drag; in the worst case, it feels like a hostile contributing environment.

**Comment by ishitatsuyuki** [comment]
I hate the Angular style, because it needlessly makes the title longer, and completely incompatible with the capitalized defacto convention.

If we have already used (kind of) Linux style, it's fine to keep using it. We don't need to enforce it in any way too.

**Comment by Fuco1** [comment]
> it feels like a hostile contributing environment.

For an extreme case of this one can look at the Emacs dev culture.  You not only have to write commit messages with tons of ridiculous "standards" applied, you also have to copy-paste the entire thing in a special changelog file (which really is just a copy of git log for... let's say historical reasons /shrug).

It seems like a small issue but in today's world when people are always in a hurry every extra (and in Emacs's case objectively useless) step creates an incentive not to contribute.

(disclaimer: I've authored more Emacs Lisp code then most people combined and I'm not hating on Emacs, I'm hating on its dev culture outside GitHub)

I agree with @jniles completely, rules like "how to write commit messages" add in fact very very little to the project (the one time in half a year when it would be useful and save the maintainer 3 minutes just does not warrant the annoyance).  This project only has 400 some commits and couple core contributors so it is 

- not high frequency (like linux kernel)
- not high contributor count (like linux kernel)

All in all it would just add bureaucracy.

**Comment by notriddle** [comment]
Well, then this issue is closed, then.

Though I maintain that a changelog file *is* useful provided it's a summary of the changes that are relevant to end-users. Things like #233 do not belong in a changelog, but things like #232 do. bors-ng's newsletter basically fulfills that role.

**Comment by Fuco1** [comment]
Indded, changelogs are useful for high level change sets as you say, and are super helpful when people are migrating to a new version with potential BC.  http://keepachangelog.com/en/0.3.0/ is a pretty good guideline for that.
