### ISSUE TITLE
Add a way to block a PR if it has a certain label

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#24]
There should be a new, optional, item in "bors.toml" for blocked label(s).

When a PR gets reviewed, the webhook controller sends a message to the batcher process. Inside that process's message handler, it should pull down the bors.toml file inside that pull request's branch (not the one in master, because: the one in master might not exist yet, we'd like to make it easy for the user to test out the label blocking feature, and we want to be consistent with the way it's already working). If the bors.toml is syntactically invalid or nonexistent, the pull request should be rejected. The pull request should also be rejected if any of the block labels are present (if the block labels key is missing, it's the same as if it was an empty list).

bors-ng itself will probably add this to its bors.toml once this feature is implemented:

    block-labels = ["S-do-not-merge-yet"]

**Comment by TheDoctorsLife** [comment]
Should ``try`` still be allowed so that they could do something like a WIP tag that prevents it from being merged but allows them to test it on the CI?

**Comment by notriddle** [comment]
Yes, `try` probably should be allowed.
