### ISSUE TITLE
delete-merged-branch race condition

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#240]
If that new feature is turned on, then we produce a race condition.

* If GitHub registers that the branch has been merged into master first, it will mark it with the purple "Merged" icon.
* If GitHub registers that the branch has been closed before it recognizes that the git operations correspond to a merge, it will mark it with the red "Closed" icon.

The thing does get merged into master correctly, but github thinks it was rudely rejected.

We want it to always give the purple Merged icon, and the best way to do it that I know of would be to have bors wait until it receives the "pull request closed" webhook from GitHub before deleting the branch.

**Comment by khodzha** [comment]
shouldnt we poll for this (for example every 10*(2^n) seconds)?

**Comment by notriddle** [comment]
GitHub sends a webhook when it marks a PR as merged, so we probably do want to use it. Once that webhook arrives, we know that the database (GitHub uses a MySQL database with transactions for Issues and PRs) has been updated.

It's possible, in principle, for the webhook to be dropped, so I guess we'd want to do polling in addition to listening for the notification. That's not necessary for a MVP, though.

**Comment by khodzha** [comment]
if i want to use both webhooks and do polling, is genserver an overkill for handling them?

**Comment by notriddle** [comment]
I would probably use a genserver for this. I don't think it's overkill.

**Comment by notriddle** [comment]
Fixed by #242
