### ISSUE TITLE
Post a warning if they try to r+ or try a PR with `[ci skip]` in the title or body

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#252]
See https://github.com/ordian/toml_edit/pull/3 for an example of how annoying the perpetual timeouts are.

**Comment by jeffparsons** [comment]
This behaviour is irritating, especially in combination with Dependabot.

Dependabot opens a PR with a list of summarised commits from upstream. Some of those commits might have "[ci skip]" in their description.

"CI skip" means absolutely nothing in our build system, but Bors predicts (wrongly) that the presence of "CI skip" in the PR description means that the PR would time out. The PR then sits around until someone manually edits the description to remove the words "CI skip".
