### ISSUE TITLE
Grab the "App URL" using the /app endpoint

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#253]
https://platform.github.community/t/an-app-api-endpoint/1967/6

This means that people setting up their instances don't have to specify the GITHUB_APP_PUBLIC_LINK.

**Comment by khodzha** [comment]
im not sure /app/:id is working yet
i have this (pic attached) app and if i understand correctly - my app id is 3839
![bors-test app](https://user-images.githubusercontent.com/1618874/29843265-19eab138-8d14-11e7-9281-b24bc943d82c.png)

yet both
```
curl -v https://api.github.com/app/3839 -H "Accept: application/vnd.github.machine-man-preview+json"
curl -v https://api.github.com/apps/bors-test -H "Accept: application/vnd.github.machine-man-preview+json"
```
return 404

**Comment by notriddle** [comment]
https://platform.github.community/t/an-app-api-endpoint/1967/11

**Comment by khodzha** [comment]
it doesnt work for private apps though

**Comment by notriddle** [comment]
Does it just not work for private apps at all, or does it only work for private apps when you authenticate as the app itself?

**Comment by khodzha** [comment]
well, `/app` works after obtaining jwt token, `/app/:id` does not, but whatever

**Comment by notriddle** [comment]
We're going to want to be authenticated as the app whenever we hit the API anyway. We get better rate limits that way. So might as well use the `/app` entrypoint.
