### ISSUE TITLE
DB timeout / crash

### ISSUE THREAD

**Issue by mithrandi** [bors-ng/bors-ng#254]
We just started trying out bors-ng internally (running our own instance), and we're getting some errors like this:
```
21:05:39.123 [error] Postgrex.Protocol (#PID<0.306.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.3011.0> timed out because it checked out the connection for longer than 15000ms
21:05:39.124 [error] GenServer #PID<0.3011.0> terminating
** (DBConnection.ConnectionError) tcp recv: closed
    (db_connection) lib/db_connection.ex:794: DBConnection.transaction/3
    (bors_worker) lib/batcher.ex:66: BorsNG.Worker.Batcher.handle_cast/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:cancel_all}}
```
They seem to be causing batches to be cancelled or marked "crash". From what I can understand, the code is doing something in a transaction and the transaction is running longer than 15 seconds so it's being timed out; I couldn't grok the code well enough to figure out exactly what it's doing in `handle_cast` though. Is there some easy way to work around this? I'm not sure if this is the consequence of being 300ms+ away from GitHub making stuff slow, or some local issue.

**Comment by notriddle** [comment]
It does sound like a combination of latency with GitHub and my own laziness keeping me from doing more reasonable transaction boundaries.

I might just remove the transaction wrapping entirely. You'll notice that the `handle_cast` and `handle_info` both use the `Repo.transaction` function. You can try removing the wrapper, making these changes:

```diff
diff --git a/apps/bors_worker/lib/batcher.ex b/apps/bors_worker/lib/batcher.ex
index abfbcfc..04628ae 100644
--- a/apps/bors_worker/lib/batcher.ex
+++ b/apps/bors_worker/lib/batcher.ex
@@ -63,7 +63,7 @@ defmodule BorsNG.Worker.Batcher do
   end

   def handle_cast(args, project_id) do
-    Repo.transaction(fn -> do_handle_cast(args, project_id) end)
+    do_handle_cast(args, project_id)
     {:noreply, project_id}
   end

@@ -144,7 +144,7 @@ defmodule BorsNG.Worker.Batcher do
     if repetition != :once do
       Process.send_after(self(), {:poll, repetition}, @poll_period)
     end
-    case Repo.transaction(fn -> poll(project_id) end) do
+    case poll(project_id) do
       {:ok, :stop} ->
         {:stop, :normal, project_id}
       {:ok, :again} ->
```

**Comment by mithrandi** [comment]
Thanks! I've redeployed with that patch applied, will see if we get any more of those errors.

**Comment by mithrandi** [comment]
This doesn't quite work (as I guess the failing tests in #256 show) because the patterns in the `case` are incorrect, as there is no longer a transaction status being added on. I'm trying again with that issue fixed.

**Comment by notriddle** [comment]
Did the adjusted patch fix it?

**Comment by mithrandi** [comment]
Looks like no errors / failures since I deployed that version, so I'd say everything is working well now :+1:
