### ISSUE TITLE
Restricting repository add/remove

### ISSUE THREAD

**Issue by ishitatsuyuki** [bors-ng/bors-ng#283]
I think the Rust organization would probably limit its use to their own repositories, so I think we may need an option to make it admin-only or more configurable one.

**Comment by notriddle** [comment]
GitHub itself supports "private" apps that only work with a particular org. Is there some reason why that won't work?

**Comment by ishitatsuyuki** [comment]
Oh, didn't notice that. It should be documented then for self hosters.
