### ISSUE TITLE
delegate r+ does not allow the PR author to bors try

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#294]
After I `bors delegate r+`, I expect that the original PR author can then `bors try` without getting permission denied errors, but it does not seem to happen. See conversation at: https://github.com/intellij-rust/intellij-rust/pull/1718#issuecomment-328502139

**Comment by khodzha** [comment]
bors must've reported `%username% can now approve this pull request` and it didnt
looks like it failed adding a delegatee, maybe pr syncing code is wrong?

@notriddle

**Comment by notriddle** [comment]
No, it didn't report that. I can see that it didn't by following the link.

**Comment by khodzha** [comment]
do you have any ideas why it didnt?
(here)[https://github.com/bors-ng/bors-ng/blob/master/apps/bors_frontend/web/command.ex#L366]
it looks like the only way to fail this is delegatee abscence?

**Comment by notriddle** [comment]
The easy answer is: boot up your test instance with the current master branch, try out delegating, then look at the logs and the database.
