### ISSUE TITLE
bors does not respond to "Bors"

### ISSUE THREAD

**Issue by jniles** [bors-ng/bors-ng#308]
This may be intended behavior, but I wanted to bring up for discussion.

On mobile browsers, my keyboard aggressively autocorrects every first line in Github's text area and capitalizes it.  This leads to commands such as "Bors r+", which seem to be unrecognized.  It will respond to a lowercase "b".

I can see how this might be useful to make sure bors doesn't do any unintended behavior and so [I have added it to the wiki](https://forum.bors.tech/t/quirks-of-how-bors-ng-parses-github-pr-comment-commands/53).  However, if it is simply a corner case, it would be nice to have it fixed!

**Comment by notriddle** [comment]
I did that on purpose so that you can avoid triggering it by using sentence case, but you're right that it makes it harder to use when your keyboard wants you to type like that...

If nobody else has an opinion on how it ought to work, I'm fine with switching to a case-insensitive match for "bors".

**Comment by notriddle** [comment]
Also, we probably have a sufficiently large set of ways to avoid accidentally triggering it...

**Comment by GustavoCaso** [comment]
@notriddle I love to help with this one.

**Comment by jniles** [comment]
@GustavoCaso, I don't believe anyone is working on it.  Go for it!
