### ISSUE TITLE
delete old history

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#313]
After about six months or so,

* A batch that is marked succeeded/failed/canceled should be deleted.
* A patch that is marked closed and/or is associated with a batch that is marked succeeded/failed/canceled should be deleted.

If people want statistics, we could dump stuff to something like S3. The point is to get the data out of high $/GiB PostgreSQL storage.

**Comment by grahamc** [comment]
So this seems to be doing the business:

```elixir
# Delete all batches older than N months which are done processing
BorsNG.Database.Repo.delete_all(from p in BorsNG.Database.Batch, where: (p.state in [ ^(:ok)] and p.updated_at < datetime_add(^NaiveDateTime.utc_now, -6, "month") ))
# Delete all the patches which are not open, and older than N months
BorsNG.Database.Repo.delete_all(from p in BorsNG.Database.Patch, where: (p.open == false and p.updated_at < datetime_add(^NaiveDateTime.utc_now, -6, "month")))
```

A third option could be deleting any old patch (older than 6mo) with no related batch. What do you think? I'm sort of inclined to just make this a `mix` task that people can call as needed, and possibly make the # of months a parameter.

**Comment by notriddle** [comment]
Yeah, that's fine. Make it a mix task, and make it accessible [the same way the migrations are](https://github.com/bors-ng/bors-ng/blob/105a3f35df95d1264b38df2c6f4ccbf0ffa9e2ef/lib/database/migrate.ex).

**Comment by grahamc** [comment]
This can be closed now
