### ISSUE TITLE
Get rid of the "successfully logged in" notification

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#315]
It doesn't really accomplish anything; you've obviously succeeded in logging in because your username showed up in the upper right corner. Let's get rid of it.

[It's in `auth_controller.ex`](https://github.com/bors-ng/bors-ng/blob/5662d6f/apps/bors_frontend/web/controllers/auth_controller.ex#L98).

**Comment by GustavoCaso** [comment]
@notriddle if no one is working I would like to help

**Comment by notriddle** [comment]
Cool, go ahead!

**Comment by notriddle** [comment]
Fixed by #316
