### ISSUE TITLE
PR status says "waiting in queue", while dashbord says "awaiting review"

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#320]
![image](https://user-images.githubusercontent.com/1711539/32321612-bc3f6820-bfd2-11e7-9b4c-34970b7ea736.png)

https://github.com/intellij-rust/intellij-rust/pull/1962

Looks like the recent r+es were lost? Travis says that there are some "linux capacity problems", so it may be the case that Travis is acting up.

**Comment by notriddle** [comment]
I guess it crashed?

**Comment by matklad** [comment]
>I guess it crashed?

Quite probably, but it would be cool if bors handled such cases more gracefully. I would be delighted to see a comment from bors, saying:

> Hey, we are experiencing some problems with merging pull requests right now, we will retry in 30 minutes.

**Comment by notriddle** [comment]
Yeah. I haven't been spending much time on bors lately (work has been nuts, and there've been other interesting oss projects to spend that limited time on), though what I have been working on is #266, which should make it easier to handle crashes in a good way.

Should get that refactoring merged in some time in December, then work on better crash handling.
