### ISSUE TITLE
Filter out reviewable.io button from commit message

### ISSUE THREAD

**Issue by torkleyy** [bors-ng/bors-ng#335]
This is very-low priority. bors uses the PR description and appends it to the merge commit message. If a repository uses reviewable.io, every PR has a reviewable button inserted into the description automatically.

Example:

```
540: fix: Formatting r=Xaeroxe,torkleyy a=Rhuagh

Newest rustfmt-nightly.

<!-- Reviewable:start -->
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/amethyst/amethyst/540)
<!-- Reviewable:end -->
```

Would be nice if that could be filtered out, but again it's very low priority :)

**Comment by notriddle** [comment]
That's actually possible already. Add these to your bors.toml file:

```toml
cut_body_after = "<!-- Reviewable:start -->"
```

**Comment by torkleyy** [comment]
Ah, thank you!
