### ISSUE TITLE
when a batch job fails, bors does not rerun

### ISSUE THREAD

**Issue by jeff-hammel-leapyear** [bors-ng/bors-ng#336]
It is my understanding that when a batch job fails, the job is divided into two sections and each are rerun.  Instead, it appears that I get two "Waiting to retry" sections on the bors status page and they never actually get retried and instead wait there indefinitely.  The only remedy that I have come up with is cancel all the jobs, find the bad parts of the batch myself, and manually `bors r+` the PRs that should be requeued.  Since this is a big part of what bors should provided, I would love to have a remedy for this issue or even a place to look to figure out what is going on.

**Comment by notriddle** [comment]
It's probably waiting an hour before retrying them. I'm leaving this open, because that's probably not a very good behaviour to have. Thanks for reminding me to fix it!
