### ISSUE TITLE
README doesn't document the format of `DATABASE_URL`

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#345]

**Comment by zimbatm** [comment]
If it's important to you, why not submit a PR?

**Comment by JensRantil** [comment]
@zimbatm Because I have no idea what format it should be in. If you could share the format for the value, I'd love to submit a PR.

**Comment by notriddle** [comment]
It's an Ecto database url, and [it's documented here](https://hexdocs.pm/ecto/Ecto.Repo.html#module-urls)

**Comment by jeffparsons** [comment]
This confused me when I was setting up my instance of Bors, too.

I was about to make a PR for this, then noticed it was already added here: 2837e6f65cff151ed96f951748e8a2b9f8a3cc93. So... guess this can be closed, then? 😄

**Comment by JensRantil** [comment]
Yep, it's fixed.
