### ISSUE TITLE
bors should (optionally?) check for a review status on a PR before batching

### ISSUE THREAD

**Issue by jeff-hammel-leapyear** [bors-ng/bors-ng#357]
Depending on the policy of a repository and business logic, it may be that reviews are required before merging.  In that case, at least optionally, `bors-ng` should be configurable not to accept `bors r+` before the reviewer has approved.  In the case that a person adds `bors r+` before reviewer(s) have approved, it is possible and not unlikely that a PR will not be approved before running CI and then bors will reject the PR at CI completion time.  Instead (at least optionally), bors should not accept an `r+` job.  `bors try` jobs should, of course, not care about this.

**Comment by grahamc** [comment]
My interpretation of this feature indicates that after fetching a list of reviews it should:

1. exclude any where the `author_association` is `NONE`. This will include (as far as I can tell) anyone who is able to push to the repo.
2. select all where the `state` is `CHANGES_REQUESTED`. This will ignore dismissed reviews, comment-only reviews, and approvals.

if the resulting list contains any reviews, skip processing.

Does this sound right?

Here are two API calls showing a variety of associations and states:

 - https://api.github.com/repos/tweag/bors-test/pulls/2/reviews
 - https://api.github.com/repos/NixOS/rfcs/pulls/25/reviews

**Comment by jeff-hammel-leapyear** [comment]
@grahamc To describe our particular setup which is not atypical, a repository has a policy such that:
at least one reviewer must have the state be `APPROVED`;  and no reviewers may have `CHANGES_REQUESTED`.  This is close to what you describe; but there is the additional caveat.  I'm not sure how to codify this for `bors.toml`; obviously `bors-ng` is not a general business logic engine.  I am unaware of any github APIs that will express the repository policy...if such exist, then that would be the correct source of truth.  Otherwise, it would be desirable to encompass the above logic in a `bors.toml` key such as `approval_required = true`.

**Comment by jeff-hammel-leapyear** [comment]
@grahamc that sounds about perfect 👍

**Comment by notriddle** [comment]
Yup, just have it always reject if there are negative reviews, and add a bors.toml option to require at least one positive review.
