### ISSUE TITLE
`required_approvals` always rejecting?

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#370]
**Background:**

What I did:

 1. Upgraded `bors-ng` to the b9770bc7af66 Docker image.
 2. Verified that `bors r+` worked on a basic pull request which modified some `README` file or something.
 2. Submitted a pull-request which added `required_approvals = 1` to my `bors.toml` file.
 3. Tried to approve it myself by commenting "bors r+" and got "👎 Rejected by too few approved reviews".
 4. Asked a colleague to "bors r+" and we again got "👎 Rejected by too few approved reviews".

**Expected:**

 * That a single approval (that is, mine) should make bors-ng merge the PR. I base this on the [reference manual](https://bors.tech/documentation/) which states

> Number of project members who must approve the PR before it is pushed to master.

**Was actually happened:**

 * Bors rejected the approval with comment "👎 Rejected by too few approved reviews"

**Workaround:**

Use something like https://github.com/tink-ab/four-eyes :-)

**Comment by notriddle** [comment]
We should probably mention that it's talking about "GitHub Reviews," not "bors r+" lines.

**Comment by JensRantil** [comment]
By "GitHub Reviews", you mean "Approved Github Reviews", right?

**Comment by JensRantil** [comment]
Closing this. See #373 to keep the scope tight.
