### ISSUE TITLE
Destination branch status check

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#372]
**Problem:** Security-related pull request checks such as [Four Eyes](https://github.com/tink-ab/four-eyes) can be disabled by modifying `bors.toml` `status` field in the pull request. 

**Proposal:** Add a `destination_branch_status` field in `status` from which statuses will be extracted from. When bors-ng is running it's tests, it extracts `destination_branch_status`es from the PR destination branch and require that they pass, too.

**Additional info:** This came out of https://github.com/bors-ng/bors-ng/issues/371#issuecomment-373729834.

**Comment by notriddle** [comment]
Bors already has two different kinds of statuses. I really don't want to end up with three.

**Comment by JensRantil** [comment]
👍I appreciate your focus on avoiding scope creep. See https://github.com/bors-ng/bors-ng/issues/371#issuecomment-374166327 for a (hopefully!) precise description what I'm trying to do. Focusing on use-cases always helps.
