### ISSUE TITLE
bors use of "Merge conflict" message is misleading

### ISSUE THREAD

**Issue by jeff-hammel-leapyear** [bors-ng/bors-ng#378]
bors notion of a merge conflict != a git merge conflict.  This is already confusing enough for most engineers (that know git but not bors).  bors means a semantic merge conflict.  However, this itself may not be true.  A batch may be canceled.  CI may fail for upstream reasons. Etc.

I would probably choose language like "(possibly) Failing..." when an event, like a cancellation, can't be detected.

**Comment by notriddle** [comment]
The merge conflict message doesn't mean the test suite failed; that's called a "Build failed." The "merge conflict" message really does mean that GitHub returned an error when bors tried to create the commit (though batching can cause a merge conflict to appear even between two PRs, even though they'd be able to merge into master just fine).
