### ISSUE TITLE
Merge commits should surface authorship information in title and avatars

### ISSUE THREAD

**Issue by jordanlewis** [bors-ng/bors-ng#382]
It would be nice if a Bors-created merge commit surfaced the authorship information of the commits being merged. For example, look at the difference between these two merges:

![image](https://user-images.githubusercontent.com/43821/37998925-a6566b56-31ee-11e8-9ff1-84c760e4e6bb.png)

The first merge clearly shows whose work is being merged, with a visual (avatar) and text (username). The bors merge hides that information. It would be great if bors commit messages also surfaced that information.

To that end, I have two suggestions: use GitHub's `Co-authored-by:` feature, and add username information to the merge commit message.

----

GitHub's [Co-authored-by feature](https://blog.github.com/2018-01-29-commit-together-with-co-authors/) would make merge commits include the avatars of the authors of the commits that are being merged. That would make it easier to see, at a glance, whose PRs were getting merged by a particular merge commit.

For example, [Bors' inaugural commit to CockroachDB](https://github.com/cockroachdb/cockroach/commit/7db3d0546f041826bbc6d398bb5d9703a66319fd) (:tada:) could have the following message:

```
Merge: add212107 21b64f78d
Author: craig[bot] <craig[bot]@users.noreply.github.com>
Date:   Tue Mar 27 21:23:39 2018 +0000

    Merge #24100

    24100: build: add bors.toml r=couchand a=couchand

    Teaches Bors to wait for a successful build on TeamCity before merging approved PRs to master.

    Contributes to #22499
    Release note (build change): Begin using Bors to automate merging PRs to master.

    Co-authored-by: Andrew Couch <github@couchand.com>
```

note the final `Co-authored-by:` line.

As far as a textual representation, there's clearly some difficulty because any given merge could have many PR authors within. As a compromise to always including authorship in the merge commit message, perhaps single-author merges could include the author's username and branch a la GitHub's merges, e.g.

```
Merge #24100 from couchand/chore/bors
```

but multi-author merges could omit the lengthy branch names, e.g.

```
Merge #12345 from 5 PRs of couchand, jordanlewis, notriddle
```

or do even more compression if the author list is really out of hand. What do you think?

Lastly, thank you for your hard work on `bors`!

**Comment by notriddle** [comment]
We should definitely put the Co-Authored-By line in the commit. I'm not sure how I feel about the others, since I know that people want to *parse* these commits so the format should try to stay consistent, but the co-author commit message that GitHub parses should definitely be added.

**Comment by bdarnell** [comment]
I'd like to include the original PR's subject line in the first line, not just the author name:

    Merge #21400: build: add bors.toml

I've found this pretty important in making sense of our commit history. 

If there are multiple PRs, this isn't possible, but I'd be tempted to give each PR in a batch its own merge commit so that the commits are still grouped and can have their own subject line.

**Comment by couchand** [comment]
The multiple PR suggestion is related to #138.

@notriddle if you don't mind, I'd like to take a look at at least implementing the Co-Authored-By lines.  I think to strategy would be to [fetch the list of commits](https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request) for each PR and then flat map them and dedupe.  Does that sound sensible?
