### ISSUE TITLE
Git hashes aren't used as the version in Docker releases

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#383]
The ones on Docker Hub aren't reporting the git commit they were based on. Since we're not really using version numbers yet, we should probably just use git commit hashes for them.

**Comment by JensRantil** [comment]
So, I'm running docker container. How can I get the hash from it? It says "Build: 0.1.0" on the bottom right in Bors, but that doesn't really help.

**Comment by notriddle** [comment]
Figured out why the docker image wasn't showing the version number. Try upgrading and it'll fix it.
