### ISSUE TITLE
History page seems to be in no particular order

### ISSUE THREAD

**Issue by couchand** [bors-ng/bors-ng#389]
From what I can tell, the History page isn't in any particular order.  Is there perhaps an `ORDER BY` that could be added judiciously to correct this?

<img width="562" alt="screen shot 2018-04-02 at 4 56 18 pm" src="https://user-images.githubusercontent.com/793969/38215787-e3918bf2-3696-11e8-8ae6-f2af8de22a82.png">

**Comment by benesch** [comment]
Oddly enough there _does_ seem to be a `sort_by`: https://github.com/bors-ng/bors-ng/blob/1e2c3ff43d659a401e5ea33ae761c636aeb8b9db/lib/web/controllers/project_controller.ex#L108

I don't have the slightest about what's going wrong.

**Comment by JensRantil** [comment]
Duplicate of #374?

**Comment by couchand** [comment]
Yep, definitely a dupe.
