### ISSUE TITLE
Listed repository yields a 404

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#408]
I just tested out #407. Good stuff! 🙏  By adding the user as a member the repository is now

 * included in dashboard.
 * listed under `/repositories`.

That said, the repository (to which I've added the member) under `/repositories` links to a 404. My proposal is that at least `/repositories/3` (or whatever identifier the repo has) is visible and possibly history and settings are presented with read-only permissions.

What do you think of this?

**Comment by notriddle** [comment]
Yes, that one flew completely over my head. Fixed that.
