### ISSUE TITLE
"Running" no job

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#412]
I think our internal bors-ng instance has ended up a weird state. See attached screenshots.

![2](https://user-images.githubusercontent.com/730342/39194714-9f0a254e-47de-11e8-91da-60133eb9001c.png)
![1](https://user-images.githubusercontent.com/730342/39194715-9f2c58b2-47de-11e8-8640-de18673067e2.png)

I expect "Running" to at least list one job.

**Comment by JensRantil** [comment]
Looks like bors-ng automatically got out of the weird state. Is this expected. Also, could the attached screenshot/crash have something to do with it?

<img width="824" alt="screen shot 2018-04-24 at 17 30 38" src="https://user-images.githubusercontent.com/730342/39197640-4db73d2e-47e5-11e8-8fbf-c7c26c0875e0.png">

**Comment by JensRantil** [comment]
We ended up in this state again.

**Comment by JensRantil** [comment]
> We ended up in this state again.

This time we had manually dismissed a single pull request review. Not sure that's something trickles out through a webhook.

The "Running" list is visible but empty. We're getting the same stacktrace as submitted in https://github.com/bors-ng/bors-ng/issues/412#issuecomment-383976313.

We've also tested

 1. making sure all/both reviewers have approved the PR and then `bors r+`.
 2. making sure all/both reviewers have approved the PR and then `bors r-` followed by `bors r+`.

We've also tested closing and reopening the PR to no avail. I now noticed that there is no empty "Running" list for the repo anymore and tested once more to do `bors r+`. Despite both/all reviewers have approved the PR (we have `required_approvals = 1`), no merge is being triggered to `staging` branch and bors-ng now presents an empty "Waiting to run" list for the repo (there's also a bunch of "Awaiting review" which are expected):

<img width="1041" alt="screen shot 2018-05-02 at 23 06 45" src="https://user-images.githubusercontent.com/730342/39549302-a0afaf7e-4e5d-11e8-9242-526f3cf2cf6e.png">

Tomorrow I think we're gonna need to close this PR and open a brand new one as something is funky with this particular one.

**Comment by notriddle** [comment]
I found a code path that could result in you getting a batch with no associated patches. You mentioned reviewers, so it's probably https://github.com/bors-ng/bors-ng/pull/418

**Comment by notriddle** [comment]
If it happens after applying this patch to your instance, please reopen this issue 🤞

**Comment by LarsAlmgren** [comment]
I've also experienced this.
