### ISSUE TITLE
Provisionally accept 'r+' before PR status satisfied

### ISSUE THREAD

**Issue by jeffparsons** [bors-ng/bors-ng#430]
Hi there! 👋 

One of the really nice things we've found about using Bors is that once a reviewer is happy with a PR's code changes, they can 'r+' it, and then (assuming all goes well) some time later `master` will contain those changes. No "babysitting PRs" involved.

We recently started using the `pr_status` option to require branches to pass a restricted set of basic tests before they are admitted into a Bors batch, in an attempt to reduce the high number of batches that people were accidentally poisoning.

This has helped overall, but the way `pr_status` currently works means that we're now babysitting PRs again, like we were before adopting Bors. I.e. if we "r+" a PR before its own tests have passed, Bors tells us:

> 👎 Rejected by PR status

So someone has to wait for the branch's own tests to pass, and then "r+" it.

**Proposal:** It seems like a more natural workflow would be to let you "r+" a PR, and then as soon as it meets all other criteria (e.g. statuses, GitHub reviews, etc.), _then_ Bors would admit it into a batch. And GitHub does appear to offer status update events, so it wouldn't require Bors to poll GitHub.

Is there some reason I've missed why rejecting the "r+" is sometimes preferable?

(We've actually now written a bot internally to approximate this proposed behaviour — but I'd love to be able to delete our hacks if this behaviour would be preferred upstream. 😁)

**Comment by JensRantil** [comment]
Duplicate of #390?

**Comment by jeffparsons** [comment]
@JensRantil Ah, yes, I suppose it is — at least in spirit. I missed that one. I could move the text of this issue into a comment on https://github.com/bors-ng/bors-ng/issues/390?

**Comment by JensRantil** [comment]
@jeffparsons If it adds additional information to what's already written in #390, sure! If not, we can close this.

**Comment by jeffparsons** [comment]
Closing in favour of https://github.com/bors-ng/bors-ng/issues/390
