### ISSUE TITLE
Seems to only load the first 30 repositories in an org

### ISSUE THREAD

**Issue by timvdalen** [bors-ng/bors-ng#44]
Is there any way to force it to read a certain repository?
Opening it as admin results in a 404.

**Comment by timvdalen** [comment]
Webhooks sent about other repositories result in a 404 as well

**Comment by notriddle** [comment]
It's probably pagination (when you add an "all repos" item for an org, it has to pull down the list of repos from GitHub, and that's probably being paginated).

**Comment by timvdalen** [comment]
Note: Adding the repo manually to the projects page works fine, but only newly opened pull requests will show up.

**Comment by notriddle** [comment]
That's because #18 hasn't been implemented yet.

**Comment by notriddle** [comment]
This should fix the first (pagination-related) problem.
