### ISSUE TITLE
bors answers to all commands but try

### ISSUE THREAD

**Issue by fredrikekre** [bors-ng/bors-ng#445]
We have activated bors over at https://github.com/JuliaLang/Pkg.jl and everything seems to work, except the `bors try` command. See here: https://github.com/JuliaLang/Pkg.jl/pull/638

Any ideas what might be the problem?

**Comment by KristofferC** [comment]
Looks like someone else is furiously trying to use `try` here as well but failing: https://github.com/ehuss/test/pull/8

**Comment by KristofferC** [comment]
Thanks for the quick fix! Is the fix deployed straight away or what is the process?

**Comment by KristofferC** [comment]
https://github.com/JuliaLang/Pkg.jl/pull/638#issuecomment-412623223

woho! 🎉

**Comment by fredrikekre** [comment]
Thanks for the quick fix!
