### ISSUE TITLE
Crash when approving pull request

### ISSUE THREAD

**Issue by TheNeikos** [bors-ng/bors-ng#455]
When I try to `bors r+` a new PR bors crashes with:

```
{{:badmatch, {:error, :get_commit_status, :check}},
 [{BorsNG.GitHub, :get_commit_status!, 2,
   [file: 'lib/github/github.ex', line: 120]},
  {BorsNG.Worker.Batcher, :patch_preflight, 3,
   [file: 'lib/worker/batcher.ex', line: 511]},
  {BorsNG.Worker.Batcher, :do_handle_cast, 2,
   [file: 'lib/worker/batcher.ex', line: 109]},
  {BorsNG.Worker.Batcher, :handle_cast, 2,
   [file: 'lib/worker/batcher.ex', line: 77]},
  {:gen_server, :try_dispatch, 4,
   [file: 'gen_server.erl', line: 601]},
  {:gen_server, :handle_msg, 5,
   [file: 'gen_server.erl', line: 667]},
  {:proc_lib, :init_p_do_apply, 3,
   [file: 'proc_lib.erl', line: 247]}]}
```

I am running the latest docker image. It is a private repo, in the config, private repos are enabled.

**Comment by notriddle** [comment]
https://forum.bors.tech/t/bors-crashes-on-r/210/5

**Comment by notriddle** [comment]
You need to grant read access to GitHub checks

**Comment by TheNeikos** [comment]
Thanks! I tried googling that, but it didn't find it.

**Comment by notriddle** [comment]
You're fine. It usually takes more than a day for Google to index stuff. (this conversation will probably help them get around to it more quickly 😄)

**Comment by TheNeikos** [comment]
For those who had to look a bit to find what you need to do:

- Go to your developer settings: https://github.com/settings/apps
- Click on the left on "Github Apps"
- Click on "Edit" for your App
- Click on "Permissions" on the left
- Set 'Checks' to at least 'read'
- Save
- Re-Authorize your app

**Comment by notriddle** [comment]
Could you copy that exact same text to the forum, too? Help make it easier to find?
