### ISSUE TITLE
maximum batch size

### ISSUE THREAD

**Issue by shmish111** [bors-ng/bors-ng#456]
Can you set a maximum batch size? The complexity of O(E log n) is pretty bad compared to O(n) if you have a reasonable chance of tests failing, see a simulation I did http://shmish111.github.io/2018/07/15/to-batch-or-not-to-batch

borg-ng would still be useful to me if I could set batch size to 1.

**Comment by qcn** [comment]
+1

Our bots like to battle each other too, this would help with merge conflicts.

**Comment by rvl** [comment]
This is sort of addressed by #839. You can set batch size 1 for a single PR by merging with:

```
bors merge single on
```

But AFAIK there is no `bors.toml` setting to configure the repo default.
