### ISSUE TITLE
Short-form of commiter name/email results in conf error

### ISSUE THREAD

**Issue by andschwa** [bors-ng/bors-ng#459]
I tried using `committer = { name = "Foo", email = "bar@baz.com" }` and got an error from Bors:

## try

# Configuration problem
bors.toml: syntax error

(Private repo else I'd link it.)

When replacing that line with:

```
[committer]
name = "Foo"
email = "bar@baz.com"
```

Bors was happy. Seems to not actually understand the short-form (or I made a mistake in the short-form that I am not spotting).

**Comment by deivid-rodriguez** [comment]
I think we had the same problem when enabling `bors-ng` on our repo: https://github.com/bundler/bundler/pull/6703.

\cc @indirect

**Comment by andschwa** [comment]
Thanks @notriddle
