### ISSUE TITLE
Instance stuck on running after crash

### ISSUE THREAD

**Issue by timvdalen** [bors-ng/bors-ng#48]
After the previous crash, one PR is stuck on 'running' even though it has already successfully completed.
Is there a way to trigger bors-ng to look at this again?

**Comment by notriddle** [comment]
Has the "staging" branch successfully completed?

**Comment by notriddle** [comment]
The easiest way to make bors drop a batch (at least right now) is to go into iex and clear the batch queue, with something like this:

    Aelita2.Batch.delete_all(Aelita2.Batch)

If you've got a bunch of stuff running on the instance, you'll need to make sure you only delete the one batch, but if nobody else is using it, it's easier not to bother writing a query.

**Comment by timvdalen** [comment]
Yes it has completed, but bors was not running when it was.
Cool, I'll try that!

**Comment by timvdalen** [comment]
Yes, this solved the 'stuck' part, feel free to close this (or keep it as a reminder to implement syncing of status).

I did run into something else later, but that is more related to my workflow:
The nubis/accepted status check is only applied to commits at the tips of branches that have an open pull request, so it will not fire for the staging commit that bors makes (and in fact has no definition there).

I was considering using bors to just '+r' PRs that had this check pending, having bors run once it turns green.
I guess I'll remove the status from my bors file and only comment once it turns green myself.

**Comment by notriddle** [comment]
Depending on what the "nubis/accepted" status check does, perhaps it could make the "bors r+" comment?

**Comment by timvdalen** [comment]
Interesting suggestion, though then I'd opt for another integration that would check all required status checks and comment.
Thanks for the feedback!
