### ISSUE TITLE
Note on force pushing

### ISSUE THREAD

**Issue by timvdalen** [bors-ng/bors-ng#49]
Add a note to the docs that bors uses force pushes when pushing to github.

I (and probably other people) have the master setup to disallow force pushing so we'll need to make an exception for bors.
While we are on the subject - why does bors need to force push?
That makes me a little uncomfortable.

**Comment by notriddle** [comment]
Bors doesn't need to force-push to master, though I specify "force" just to avoid crashing. This very repo has a protected master branch.

It will need to force-push to staging, but it's pretty obvious why that is.

**Comment by timvdalen** [comment]
I see, I think I figured out what was going wrong.

I had the branch protected with specific pushers.
GitHub does not allow you to (currently) add an integration user as a specific user so I turned that off.
I turned off force pushing to debug and I see the crashes on staging now.
bors just merged the first PR to master, so my install is going in the right direction :)

Thanks for the work on this and the help!

**Comment by notriddle** [comment]
Thanks for your help! I'll make a note about how it needs to be able to force-push to staging.

**Comment by timvdalen** [comment]
Just checked and it does seem to try to force push to master - I'm not sure how our configurations differ.

When I protect the master branch, I get this response for the master commit:
```
{\"message\":\"Cannot force-push to a protected branch\",\"documentation_url\":\"https://help.github.com/articles/about-protected-branches\"}
```

If I lift the protection and re-send the webhook for the status change, all is well and I see the merge commit on master.

**Comment by notriddle** [comment]
[Added a note to the wiki](https://github.com/bors-ng/bors-ng/wiki/Why-isn%27t-bors-working%3F)
