### ISSUE TITLE
Add the Codeship --skip-ci flag to the staging.tmp commit messages

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#51]
"staging.tmp" should not run in CI. If bors detects that it is running, it produces a warning with some information about how to fix it.

bors currently only does this for Travis CI and AppVeyor (added with PR #43). It should do it for Codeship, too.

**Comment by timvdalen** [comment]
For Codeship, the only way to completely skip CI is by adding a term to the commit message of the tmp commit: https://documentation.codeship.com/basic/getting-started/skipping-builds/

**Comment by notriddle** [comment]
Okay, then the best way to fix this would be to make the staging.tmp message always contain that magic string.

There are two places it would need to be handled; in the webhook controller, under the status handler (so that the message still matches), and in the batcher (where the message is generated).
