### ISSUE TITLE
Jenkins support

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [bors-ng/bors-ng#518]
Does Bors has support for Jenkins? 

Looking at the code I can only see Travis-CI, AppVeyor, Circle-ci and CodeShip.

**Comment by notriddle** [comment]
It doesn't have any special support, but you can make it work the same way you'd make BuildBot work. Configure the GitHub plugin to set a build status on the staging branch, then set the bors.toml to read from that same status.

**Comment by leandroBorgesFerreira** [comment]
Thanks for the Fast response. I'll do it

**Comment by JensRantil** [comment]
Can this issue be closed, then?

**Comment by notriddle** [comment]
And, by the way, I'm pretty sure bors *doesn't* work with GoCD. At least, I couldn't find a way in their documentation to report a commit status back for a branch (they have a plug-in for GitHub Pull Requests, but I couldn't find a way to do report a Status on a branches).

**Comment by notriddle** [comment]
CC @lan-nguyen91

OpenEnclave is using bors-ng with Jenkins, for example.

* [This is their Jenkins configuration](https://github.com/Microsoft/openenclave/tree/82b178f/.jenkins)
* [This is their bors configuration](https://github.com/Microsoft/openenclave/blob/82b178f/bors.toml)
