### ISSUE TITLE
Add [skip ci] in all places where [ci skip] is added

### ISSUE THREAD

**Issue by phil-opp** [bors-ng/bors-ng#522]
The `[ci skip]` string is added to commit messages of temporary commits to avoid testing them on various CI systems. One system where this doesn't work is Netlify, because [they use `[skip ci]`](https://www.netlify.com/docs/continuous-deployment/#skipping-a-deploy) instead of `[ci skip]`. This would be relatively easy fixable by just adding both tags to the commit message.

**Comment by DilumAluthge** [comment]
I can work on this.

**Comment by DilumAluthge** [comment]
See pull request #652
