### ISSUE TITLE
Useless with branch protection

### ISSUE THREAD

**Issue by jethrogb** [bors-ng/bors-ng#576]
Because of a [bug in GitHub](https://platform.github.community/t/repositories-which-have-protected-branches-with-push-restrictions-have-no-ability-to-grant-push-rights-to-integrations/1376/56) this app is useless with branch protection enabled.

**Comment by jethrogb** [comment]
The GitHub UI is not at all clear about this, but I suppose this is the recommended branch protection configuration for use with bors:
![image](https://user-images.githubusercontent.com/1132307/50898166-58ab7f80-1434-11e9-90bf-60aa237e76c2.png)
---
Note that the requirement “Require status checks to pass before merging” doesn't appear to have anything to do with merging, it applies to all forms of modifying the branch.

**Comment by notriddle** [comment]
Yeah, that's the recommendes setup.
