### ISSUE TITLE
Should CircleCI default config use regexp?

### ISSUE THREAD

**Issue by deivid-rodriguez** [bors-ng/bors-ng#598]
I'm trying out bors-ng at https://github.com/activeadmin/activeadmin/pull/5548, and I wonder why it doesn't just work.

I'm wondering, since we use CircleCI workflows where each check has the form "ci/circleci: <name_of_the_job>", whether [the default config for the CircleCI 2.0 config file](https://github.com/bors-ng/bors-ng/blob/1dba5c5ca243e481ccf58b8f90764628e353e487/lib/worker/batcher/get_bors_toml.ex#L29) should use a regexp such as `"ci/circle%"`. Could that be the culprit or does it sound like something else?

Thanks!

**Comment by notriddle** [comment]
Yes, that is the culprit. It should be changed.

**Comment by deivid-rodriguez** [comment]
Still not working afte the fix. What I did was enabling the github app, creating a `trying` remote branch in the repo, and commenting `@bors try` on a PR. There's no `bors.toml` file but I was expecting autodetection to work. Am I missing some steps?

**Comment by notriddle** [comment]
Drop the `@`. It's just `bors try` when you use this version.

**Comment by notriddle** [comment]
Okay, looking at what happened in your PR. It looks like bors got the message, but CircleCI didn't actually run on the `trying` branch. You can see it by looking at the ❌ next to the commit that bors made, and the fact that it only lists Lint CI.

**Comment by deivid-rodriguez** [comment]
Yeah, I noticed that! Maybe #599 was incorrect and I actually broke it? The initial problem of bors not listening to me was due to the incorrect username after all.
