### ISSUE TITLE
Bors adds only the 30 first collaborators of a repository to reviewers list

### ISSUE THREAD

**Issue by newtonbeck** [bors-ng/bors-ng#600]
I work in a repository with more than 30 collaborators who can comment `bors r+` command to Pull Requests. The issue we are facing is `bors r+` is available to only the first 30 collaborators returned by the GitHub API. 

The other users receive the following message from Bors when commenting `bors r+`:

```
🔒 Permission denied

Existing reviewers: click here to make newtonbeck a reviewer
```

It seems Bors is not correctly paginating on GitHub's API response.

**Comment by notriddle** [comment]
Yeah, that's what happens when I switch to a library that changes the default case for HTTP headers...
