### ISSUE TITLE
Shorten delegate to d?

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#615]
I find that I use `bors delegate+` a lot: almost every PR has some minor issues, but most of PRs have *only* minor issues, so "r=me with nits fixed" is a common outcome of the review. `bors delegate+` is very handy in this situation: you don't need to review PR the second time, and you give a strong signal of trust to the contributor.

The only problem is that delegate is a long word to type, so I feel stressed when I try to type it without misspellings :) 

I wish I could

bors d+

Given that bors replies with a helpful message, I think it's OK that d, by itself, is not self-explanatory?

**Comment by tommilligan** [comment]
Opened #727.
