### ISSUE TITLE
Repository listing order improvement

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#639]
I have a repository with a long list of pull requests. Every time I visit https://www.mybors.com/repositories/42 it lists >40 pull requests and my most common use-case is to look at the "Running" and/or "Waiting to run". Since those lists generally are bound to be shorter, how about moving the _before_ "Awaiting review". My proposal is the following order:

 1. Running
 2. Waiting to run
 3. Awaiting review

**Comment by JensRantil** [comment]
Example of how it looks today for me:

![image](https://user-images.githubusercontent.com/730342/57465234-7bcd2b00-727e-11e9-9422-7d38a12db496.png)

**Comment by umamaistempo** [comment]
Forgot to incluse a `closes #639` on the PR. The #658 PR "fixes" this by prioritizing transient states on presentation (waiting and running). @JensRantil this can be closed

**Comment by JensRantil** [comment]
Sweet! Thanks! 😍
