### ISSUE TITLE
Merging a PR does not close it, or its associated issues

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#64]
This is a bug in GitHub; it shouldn't even be possible to have a PR that's merged but not closed.

* They've already been notified about it.
* They've successfully reproduced it.
* They're going to fix it at some point; they just haven't yet.

**Comment by notriddle** [comment]
https://platform.github.community/t/pushing-a-pull-request-doesnt-close-it/1112/2

**Comment by Turbo87** [comment]
@notriddle could this be worked around by trying to close the PR after it was merged?

**Comment by notriddle** [comment]
This part of it could be worked around, but this bug seems to have a lot of related pieces of fallout.

* The PR is not closed.
* Issues mentioned with "Fixes #XXX" are not closed.
* Pages are not rebuilt.

My guess is that there's some internal PubSub mechanism that GitHub uses to run a bunch of jobs when you push to a repo, and the integration path isn't pushing to it. I don't want to reimplement the "Fixes #XXX" functionality from GitHub, and I can't trigger pages rebuilding (there's no API to do it), so I don't see the point of working around this one problem. They have to fix this bug eventually.

**Comment by frewsxcv** [comment]
bors-ng is doing something different from homu regarding this, as homu seems to merge+close pull requests just fine. Maybe homu is working around this somehow?

**Comment by notriddle** [comment]
The bug is related to the fact that bors is an Integration rather than a user.

I've diagnosed this problem using cURL. If I use an Installation Token, the bug shows up. If I use a user Personal Access Token (like homu does), the bug does not show up.

If you have an iex session into a running instance of bors-ng, you can get an Installation Token by running `Aelita2.GitHub.Server.get_installation_token!(number)`, then try using it with cURL or the git CLI. It won't work the same as a PAT.
