### ISSUE TITLE
Add a "red flag" for patches that are associated with multiple incomplete batches

### ISSUE THREAD

**Issue by notriddle** [bors-ng/bors-ng#65]
If there are multiple waiting-or-running batches with the same patch in them, it's a sign that something has gone wrong, because a patch should not be queued up multiple times. This should be added along with the orphaned-project check that is already there.

**Comment by notriddle** [comment]
This feature is going to be centered around these files:

* [`admin_controller.ex`](https://github.com/bors-ng/bors-ng/blob/c767158/apps/bors_frontend/web/controllers/admin_controller.ex) is where the routing into it is going to happen. You're also probably going to create a template for it.
* The query itself should probably go in the [`patch.ex`](https://github.com/bors-ng/bors-ng/blob/c767158/apps/bors_database/lib/project.ex) file.

**Comment by kimsaehun** [comment]
I would like to slowly start working on this issue.

May I have this issue assigned to me please?

**Comment by notriddle** [comment]
Done. Have fun! :+1:

**Comment by kimsaehun** [comment]
I've been looking at how to [add some test data](https://bors.tech/devdocs/bors-ng/BorsNG.WebhookController.html) and I have a question about the `{:installation, 91}`. 

I found the file [installation.ex](https://github.com/bors-ng/bors-ng/blob/90e312326828560e7463900eff7d7e39f9dca3f6/apps/bors_database/lib/installation.ex) and it seems to be related to GitHub apps, but I'm not quite sure what it is, what its purpose is, and why it's being stored.

Could you explain what `installation` is and why it's specifically set to 91 to me please?

**Comment by notriddle** [comment]
My choice of number is arbitrary. It's only important that it match up with the `installation_xref`.

As for what they are; installations are a concept from the [GitHub Apps API](https://developer.github.com/apps/). An installation is a link between a repository owner (either a user or an org) plus the app; bors only really uses it to authenticate, since it never does much between two repos with the same owner.
