### ISSUE TITLE
When a user is both a Reviewer and a Member, the repository is listed twice in their repositories list

### ISSUE THREAD

**Issue by jmesmon** [bors-ng/bors-ng#657]
To some extent, it doesn't make sense to have the same user be a Reviewer and a Member, but it's not clear that it's harmful.

Some mechanism to avoid listing the repo twice (by some solution that just deals with a user being both a member and reviewer, or by some mechanism which prevents/migrates/etc users that are in both to just be reviewers) would be nice to avoid confusion.

**Comment by umamaistempo** [comment]
:thinking: 

On which page ?

**Comment by umamaistempo** [comment]
Oh, found out the bug. Will issue a PR soon :)
