### ISSUE TITLE
Feature request: Sort the list of repos alphabetically

### ISSUE THREAD

**Issue by DilumAluthge** [bors-ng/bors-ng#663]
I have installed Bors on quite a few repositories. Currently, when I go to the list of repositories ([https://app.bors.tech/repositories](https://app.bors.tech/repositories)), the repositories are sorted in (I believe) the order in which Bors was installed. This makes it a little difficult to navigate a long list of repositories.

Could we instead sort the list of repositories in descending alphabetical order?

**Comment by umamaistempo** [comment]
:+1: Will take a look at this later today :)

I think that it is more logical to have an order, the most obvious one being A-Z.

However it will not be configurable (atleast at first)
