### ISSUE TITLE
Merging a pull request where a CODEOWNERS owner hasn't approved leads to crash

### ISSUE THREAD

**Issue by JensRantil** [bors-ng/bors-ng#674]
See attached example crash from the repository "History" tab:

![Screenshot 2019-06-27 at 14 02 01](https://user-images.githubusercontent.com/730342/60264729-38895300-98e4-11e9-8618-ec1615d34558.png)

Expected: That bors-ng would make a comment in the PR saying something like "code owner has not approved".

cc @umamaistempo @zegl

**Comment by umamaistempo** [comment]
Thank you for this. I was about to check the cause of the 422 error (which is obviously about permission). With this it's clearer that one of those things can be the github configuration on codeownership. I'll add a case to respond such crash with a comment like "Bors failed to merge because GitHub did not allow the merge to be completed. Some configuration is not allowing the merge, it can be a lack of permission for the bors app or something like codeowner". Naturally better written :P

**Comment by JensRantil** [comment]
Perfect!

**Comment by JensRantil** [comment]
...just double checking - GitHub are not bundling some specific reason for 422 error? If so, we could be more specific in feedback to user.

**Comment by umamaistempo** [comment]
IDK, I do not have access to github API, but yesterday notriddle talked with me about using heroku for this debugging part. If it includes any info (which I bet it does), I'll try to include it here :)

**Comment by umamaistempo** [comment]
@notriddle could you provide me "triage" access to the repo ? It's a beta feature that would allow me to put myself as the assignee of a task and having that bound to me makes it easier for me to remember to do it :)

Thanks

**Comment by JensRantil** [comment]
Worth pointing out that when the PR gets "cancelled" Bors seem not to notify with a message in the PR at all.

**Comment by DilumAluthge** [comment]
Bump @umamaistempo Are you still working on a feature in which Bors would post a comment on the pull request thread if a GitHub 422 error was encountered while trying to push?

**Comment by umamaistempo** [comment]
Hello, sorry, I got caught away last weeks on a Data Modeling Lib on Java. This week I am planning to do some Bors, so I will certainly be fixing this very soon :)

**Comment by DilumAluthge** [comment]
Hi @umamaistempo any update on this?

**Comment by JensRantil** [comment]
Given that #725 has been merged and #754 is the outstanding issue I guess this can safely be closed.
