### ISSUE TITLE
Usage with Github Actions

### ISSUE THREAD

**Issue by MikailBag** [bors-ng/bors-ng#730]
How should I use Bors, if I use Github actions for CI?
The problem is, I can't find what should I put in 'status' field in bors.toml.

**Comment by samueldple** [comment]
I've resolved this - You use the name that comes after the name of the job but before the trigger. So if you have an action whose check appears as `Rust / Build (push)` the status would be "Build". See my `bors.toml` in the PR referening this issue above for an example.

**Comment by MikailBag** [comment]
Well, I have another question/problem.
It seems that if job specified in `status` was not run, because some needed job failed, then Bors does not detect build as failed. Instead, build simply times out. example commit: https://github.com/MikailBag/jjs/commit/88cfaad18fdeb51f178336e764c823289d2ec407
