### ISSUE TITLE
bors delegate+ should explain how to approve the PR

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#748]
The delegation process looks like this at the moment:

![image](https://user-images.githubusercontent.com/1711539/64937168-e8c28400-d861-11e9-9e89-bc42130e91c8.png)

unless they are already familiar with bors, there's now way the delegatee can figure out that they need to respond with `bors r+`. It would be awesome if the "approve" word in borses comment was a hyperlink pointing to the docs.

**Comment by notriddle** [comment]
Seems like a good first issue for someone to work on. The code for this is [down at the bottom of command.ex](https://github.com/bors-ng/bors-ng/blob/master/lib/web/command.ex#L439)

**Comment by DilumAluthge** [comment]
See https://github.com/bors-ng/bors-ng/pull/755
