### ISSUE TITLE
Batch with PRs with different CodeOwners lead to crash

### ISSUE THREAD

**Issue by gmendonca** [bors-ng/bors-ng#754]
Situation:
 - PR 1 has files modified that team 1 is the code owner of them
 - PR 2 has files modified that team 2 is the code owner of them
 - When batched together the batch fails saying that with the 422 code (related to https://github.com/bors-ng/bors-ng/issues/674) that the team 1 hasn't  approved.
 - However if I merge them separately with bors, it goes without a problem

My hypothesis is maybe Github fails to recognise the rightful code owner for each PR and instead thinks of them as a single thing and then check each PR looking for the code owner of all files modified.

I don't think https://github.com/bors-ng/bors-ng/issues/681 will help in this scenario as both will get reschedule in the same batch again.

**Comment by MarkSRobinson** [comment]
I've hit this problem before.  The solution it to turn off the GitHub review requirements, and enforce it solely through bors w/ https://github.com/bors-ng/bors-ng/pull/725 applied.

**Comment by gmendonca** [comment]
Uhmmm, @MarkSRobinson  after merging https://github.com/bors-ng/bors-ng/pull/718 I cannot use both Squash merge and Codeowners options together. And I think what you just said should solve both problems. I'll give it a try.

**Comment by gmendonca** [comment]
Closing it, as solely relying on bors solved the problem. I'll update bors documentation as well.
