### ISSUE TITLE
Bors crashed after `bors r+`

### ISSUE THREAD

**Issue by deivid-rodriguez** [bors-ng/bors-ng#783]
Hello!! Thanks for bors-ng, it's very helpful to us!

After `@bundlerbot r+` (our "alias" to `bors r+`), we never got a status check back from bors-ng. When clicking on the link to the bors build, I see that bors-nng crashed crashed with the following error:

```
{{:badmatch, {:error, :merge_branch, 403}},
  [
    {BorsNG.GitHub, :merge_branch!, 2,
      [file: 'lib/github/github.ex', line: 95]},
    {Enum, :"-reduce/3-lists^foldl/2-0-", 3,
      [file: 'lib/enum.ex', line: 1925]},    
    {BorsNG.Worker.Batcher, :start_waiting_batch, 1,
      [file: 'lib/worker/batcher.ex', line: 275]},    
    {BorsNG.Worker.Batcher, :poll_, 1,
      [file: 'lib/worker/batcher.ex', line: 202]},    
    {BorsNG.Worker.Batcher, :handle_info, 2,
      [file: 'lib/worker/batcher.ex', line: 184]},
    {:gen_server, :try_dispatch, 4,
      [file: 'gen_server.erl', line: 637]},
    {:gen_server, :handle_msg, 6,
      [file: 'gen_server.erl', line: 711]},
    {:proc_lib, :init_p_do_apply, 3,
      [file: 'proc_lib.erl', line: 249]}  
]}
```

References rubygems/rubygems#2964.

**Comment by notriddle** [comment]
If bors is getting a `403` error, that usually means something weird is configured with your protected branches settings. What do you have it set for?

**Comment by bronzdoc** [comment]
@notriddle this is our `bors.toml`

https://github.com/rubygems/rubygems/blob/master/.github/bors.toml

**Comment by DilumAluthge** [comment]
@bronzdoc Can you do the following steps:
1. Go to https://github.com/rubygems/rubygems/settings/branches
2. Under the `Branch protection rules` heading, look for the row that matches the `master` branch, and click on the `Edit` button in that row.
3. Post a screenshot of that entire page.

**Comment by bronzdoc** [comment]
I'll @notriddle @DilumAluthge i'll get back with that as soon as i get access to see it.

**Comment by bronzdoc** [comment]
@notriddle @DilumAluthge 
![Screen Shot 2019-10-28 at 12 39 12 PM](https://user-images.githubusercontent.com/4595174/67707417-02d2a480-f980-11e9-8806-67cc854876de.png)

**Comment by indirect** [comment]
Hmmmm... maybe it is that we have "Require status checks to pass before merging" but there are not any status checks checked? Does that somehow break Bors but only for one PR? 😬

**Comment by bronzdoc** [comment]
@indirect It has been always been like that isn't? and it was working before 🙊

**Comment by DilumAluthge** [comment]
The screenshot that you posted does not show the entire page. Can you upload multiple screenshots that cover the entire page?

**Comment by indirect** [comment]
@DilumAluthge There are many statuses shown there, but I scrolled through and they are all unchecked.

**Comment by DilumAluthge** [comment]
I meant the rest of the settings page. There are other settings below the list of statuses.

**Comment by notriddle** [comment]
It doesn't sound like a branch protection problem, since you've had successful merges both before and after this. It's intermittent.

I have to admit, I'm stumped.

**Comment by DilumAluthge** [comment]
Are you using the latest version of Bors.

If I am not mistaken, the latest version of Bors will print the full text of the 403 error message, which is helpful for debugging.

**Comment by DilumAluthge** [comment]
If it’s intermittent, I wonder if they’re hitting some kind of rate limit. I believe that get hub returns a 403 error when you exceed the rate limit.

**Comment by deivid-rodriguez** [comment]
From looking at the places where we're seeing this problem, it seems like this happens when you instruct the bot to merge a PR+ immediately after a force-push? Definitely related for force-pushes as @bronzdoc mentioned in https://github.com/rubygems/rubygems/pull/2901#issuecomment-548168525.

**Comment by DilumAluthge** [comment]
Can you go to your Bors dashboard and let me know what build of Bors you are running? It will be in the bottom right hand corner when you open the Bors dashboard.

**Comment by deivid-rodriguez** [comment]
Also, yeah, we have updated our bors-ng installation (thanks @indirect! :)), and the error is now more verbose apparently:
```
{%Postgrex.Error{
  connection_id: 32027,
  message: nil,
  postgres: %{
    code: :undefined_column,  
    file: "parse_relation.c",
    line: "3293",
    message: "column a0.arguments does not exist",
    pg_code: "42703",
    position: "110",
    routine: "errorMissingColumn",
    severity: "ERROR",
    unknown: "ERROR"
  }
},
[
  {Ecto.Adapters.SQL, :execute_and_cache, 7,
   [file: 'lib/ecto/adapters/sql.ex', line: 431]},
  {Ecto.Repo.Queryable, :execute, 5,
   [file: 'lib/ecto/repo/queryable.ex', line: 133]},
  {Ecto.Repo.Queryable, :all, 4,
   [file: 'lib/ecto/repo/queryable.ex', line: 37]},
  {BorsNG.Worker.Attemptor, :do_handle_cast, 2,
   [file: 'lib/worker/attemptor.ex', line: 95]},
  {BorsNG.Worker.Attemptor, :handle_cast, 2,
   [file: 'lib/worker/attemptor.ex', line: 62]},
  {:gen_server, :try_dispatch, 4,
   [file: 'gen_server.erl', line: 637]},
  {:gen_server, :handle_msg, 6,
   [file: 'gen_server.erl', line: 711]},
  {:proc_lib, :init_p_do_apply, 3,
   [file: 'proc_lib.erl', line: 249]}
]}
```

**Comment by deivid-rodriguez** [comment]
The dashboard says `build: 0.1.0`, which is a broken link to https://github.com/bors-ng/bors-ng/tree/v0.1.0.

**Comment by indirect** [comment]
For the record, we are running 23c6cceb8af277a4081c34d3c3b83b918c70ea0b. I must have somehow messed up running the migration when I deployed, maybe I ran it before the deploy had fully finished or something. Anyway, we have migrated now!

@deivid-rodriguez you'll probably need to check on the error again now to see if the new version fixed it or changed it.

**Comment by deivid-rodriguez** [comment]
Ok, I'm going to check out how bors is doing for us now, I report back here if the problems persist.

**Comment by deivid-rodriguez** [comment]
Ok, so now I got this error:

```
{{:badmatch, {:error, :post_commit_status}},
 [
   {BorsNG.GitHub, :post_commit_status!, 2,
     [file: 'lib/github/github.ex', line: 227]},
   {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,
     [file: 'lib/worker/batcher.ex', line: 454]}, 
   {BorsNG.Worker.Batcher, :handle_cast, 2,  
     [file: 'lib/worker/batcher.ex', line: 83]},  
   {:gen_server, :try_dispatch, 4,    
     [file: 'gen_server.erl', line: 637]},  
   {:gen_server, :handle_msg, 6,
     [file: 'gen_server.erl', line: 711]},  
   {:proc_lib, :init_p_do_apply, 3, 
     [file: 'proc_lib.erl', line: 249]}
 ]}
```

And this time I didn't force push at all. The only "noticiable" thing about it is that there was a small time gap between the moment when CI went green and the moment when I posted the comment to instruct the bot to merge the PR.

**Comment by deivid-rodriguez** [comment]
Same error (at least very similar) happened again (the one in the original message), but it now includes more information:

```
{{:badmatch,
  {:error, :merge_branch,
   %Tesla.Env{
     __client__: %Tesla.Client{
       adapter: {Tesla.Adapter.Httpc, :call,
        [
          [
            ssl: [
              verify: :verify_peer,
              verify_fun: {&:ssl_verify_hostname.verify_fun/3,
               [check_hostname: 'api.github.com']},
              cacertfile: '/app/_build/prod/lib/certifi/priv/cacerts.pem'
            ]
          ]
        ]},
       fun: nil,
       post: [],
       pre: [
         {Tesla.Middleware.BaseUrl, :call,
          ["https://api.github.com"]},
         {Tesla.Middleware.Headers, :call,
          [
            [
              {"authorization",
               "token v1.1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"},
              {"accept", "application/vnd.github.v3+json"},
              {"user-agent", "bors-ng https://bors.tech"}
            ]
          ]},
         {Tesla.Middleware.Retry, :call,
          [[delay: 100, max_retries: 5]]}
       ]
     },
     __module__: Tesla,
     body: "{\"message\":\"Resource not accessible by integration\",\"documentation_url\":\"https://developer.github.com/v3/repos/merging/#perform-a-merge\"}",
     headers: [
       {"date", "Sat, 04 Jan 2020 18:14:24 GMT"},
       {"server", "GitHub.com"},
       {"content-length", "137"},
       {"content-type", "application/json; charset=utf-8"},
       {"status", "403 Forbidden"},
       {"x-ratelimit-limit", "7000"},
       {"x-ratelimit-remaining", "6985"},
       {"x-ratelimit-reset", "1578165182"},
       {"x-github-media-type", "github.v3; format=json"},
       {"access-control-expose-headers",
        "ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type"},
       {"access-control-allow-origin", "*"},
       {"strict-transport-security",
        "max-age=31536000; includeSubdomains; preload"},
       {"x-frame-options", "deny"},
       {"x-content-type-options", "nosniff"},
       {"x-xss-protection", "1; mode=block"},
       {"referrer-policy",
        "origin-when-cross-origin, strict-origin-when-cross-origin"},
       {"content-security-policy", "default-src 'none'"},
       {"x-github-request-id",
        "84D6:449A:222A7AB:4EE25E6:5E10D5FF"}
     ],
     method: :post,
     opts: [],
     query: [],
     status: 403,
     url: "https://api.github.com/repositories/614070/merges"
   }}},
 [
   {BorsNG.GitHub, :merge_branch!, 2,
    [file: 'lib/github/github.ex', line: 124]},
   {Enum, :"-reduce/3-lists^foldl/2-0-", 3,
    [file: 'lib/enum.ex', line: 1940]},
   {BorsNG.Worker.Batcher, :start_waiting_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 279]},
   {BorsNG.Worker.Batcher, :poll_, 1,
    [file: 'lib/worker/batcher.ex', line: 204]},
   {BorsNG.Worker.Batcher, :handle_info, 2,
    [file: 'lib/worker/batcher.ex', line: 186]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 637]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 711]},
   {:proc_lib, :init_p_do_apply, 3,
    [file: 'proc_lib.erl', line: 249]}
 ]}
```

Reference: https://github.com/rubygems/rubygems/pull/3064

**Comment by deivid-rodriguez** [comment]
The error seems reproducible at the moment on that PR, since I retried bors there, and the error happened again.

**Comment by RalfJung** [comment]
I think I am [seeing the same problem in xargo](https://app.bors.tech/repositories/5730/log):
```
{{:badmatch, {:error, :post_commit_status}},
 [
   {BorsNG.GitHub, :post_commit_status!, 2,
    [file: 'lib/github/github.ex', line: 227]},
   {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 535]},
   {BorsNG.Worker.Batcher, :handle_cast, 2,
    [file: 'lib/worker/batcher.ex', line: 90]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 637]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 711]},
   {:proc_lib, :init_p_do_apply, 3,
    [file: 'proc_lib.erl', line: 249]}
 ]}
```

**Comment by deivid-rodriguez** [comment]
Exact same error again as the one I mentioned in https://github.com/bors-ng/bors-ng/issues/783#issuecomment-570892326 on a [recent rubygems PR](https://github.com/rubygems/rubygems/pull/3167).

**Comment by deivid-rodriguez** [comment]
The error we're getting now is slightly different from the original error I reported, so I'm going to close this in favor of #806, which seems like exactly the problem we've been running into lately.
