### ISSUE TITLE
Upgrade failed on Heroku with npm error

### ISSUE THREAD

**Issue by milesgould** [bors-ng/bors-ng#797]
We have a private Bors instance running on Heroku. This morning, we tried to upgrade it with `git push heroku master` from commit 0b7d6e1c to commit 379f160, but the upgrade failed with the error
```
npm WARN checkPermissions Missing write access to node_modules/phoenix
npm WARN checkPermissions Missing write access to node_modules/phoenix_html
npm WARN assets No description
npm WARN assets license should be a valid SPDX license expression
npm ERR! path node_modules/phoenix
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access 'node_modules/phoenix'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     /app/.npm/_logs/2019-11-12T11_36_16_979Z-debug.log
 !     Push rejected, failed to compile Phoenix app.
 !     Push failed
```
[Full build log here](https://github.com/bors-ng/bors-ng/files/3836891/build.log).

We tried the following, with no success:
 - upgrading the Heroku stack from `heroku-16` to `heroku-18`
 - upgrading the buildpacks for Elixir and Phoenix
 - upgrading Elixir to 1.9.4 (there were warnings that edeliver requires Elixir >= 1.9.0)

We were able to upgrade as far as commit e41b105 (#678) - `git bisect` gives the first failing commit as 76d46a2, "Switch from brunch to webpack", from #687.

Any idea what's going on? Is there some extra upgrade step we're missing?

**Comment by notriddle** [comment]
Yeah, you should probably [clear the heroku build cache.](https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache)

**Comment by milesgould** [comment]
That's fixed it - thanks very much!

**Comment by aaronjensen** [comment]
I'm getting this as well on master, even after clearing my build cache. I have not upgraded elixir, since it looks like that's hard coded in the repo. Should I?
