### ISSUE TITLE
Check all CODEOWNERS locations

### ISSUE THREAD

**Issue by zegl** [bors-ng/bors-ng#803]
According to the GitHub documentation, codeowners can be defined at three locations.

> To use a CODEOWNERS file, create a new file called CODEOWNERS in the root, docs/, or.github/ directory of the repository, in the branch where you'd like to add the code owners.

bors only checks `.github/CODEOWNERS`  ([code](https://github.com/bors-ng/bors-ng/blob/fcec51b5f6e5a691d3e310bd35ba7b74e55b667f/lib/worker/batcher/get_code_owners.ex#L12)).

I believe that bors should check all three locations for the presence of a CODEOWNERS file.

I also think that it would be a good idea to crash/abort if `use_codeowners` is enabled, but no codeowners file could be found.

**Comment by quicksnap** [comment]
We were snagged by this. Silent failure when we had CODEOWNERS in root. Easy enough for us to move, though!
