### ISSUE TITLE
Required status check "bors" is pending

### ISSUE THREAD

**Issue by zegl** [bors-ng/bors-ng#866]
Using the public hosted version of bors, I've started to see failures like this today, `r+` worked fine yesterday.

PR: https://github.com/zegl/kube-score/pull/218

Branch protection is enabled on `master`, and only requires the `bors` status.

```
{{:badmatch,
  {:error, :push, 422,
   "{\"message\":\"Required status check \\\"bors\\\" is pending.\",\"documentation_url\":\"https://help.github.com/articles/about-protected-branches\"}"}},
 [
   {BorsNG.Worker.Batcher, :complete_batch, 3,
    [file: 'lib/worker/batcher.ex', line: 553]},
   {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 507]},
   {BorsNG.Worker.Batcher, :handle_cast, 2,
    [file: 'lib/worker/batcher.ex', line: 85]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 637]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 711]},
   {:proc_lib, :init_p_do_apply, 3,
    [file: 'proc_lib.erl', line: 249]}
 ]}
```

**Comment by zegl** [comment]
I'm not seeing similar errors when using a private instance of bors, that's built from an earlier commit.

Since this bug is new, I'm suspecting that https://github.com/bors-ng/bors-ng/pull/859 might be the culprit.

**Comment by Ogeon** [comment]
I'm having the same problem for https://github.com/Ogeon/palette/pull/164.

**Comment by TomVasile** [comment]
We are also experiencing this issue using the public hosted version.

{{:badmatch,
  {:error, :push, 422,
   "{\"message\":\"Required status check \\\"bors\\\" is pending.\",\"documentation_url\":\"https://help.github.com/articles/about-protected-branches\"}"}},
 [
   {BorsNG.Worker.Batcher, :complete_batch, 3,
    [file: 'lib/worker/batcher.ex', line: 553]},
   {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 507]},
   {BorsNG.Worker.Batcher, :handle_cast, 2,
    [file: 'lib/worker/batcher.ex', line: 85]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 637]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 711]},
   {:proc_lib, :init_p_do_apply, 3,
    [file: 'proc_lib.erl', line: 249]}
 ]}
