### ISSUE TITLE
Add a comment when PR is approved

### ISSUE THREAD

**Issue by badboy** [bors-ng/bors-ng#87]
See for example https://github.com/rust-lang/rust/pull/39431#issuecomment-277549982
Then the user at least knows that the bot got it and will merge it eventually.

**Comment by notriddle** [comment]
Would confirming it with a CI status be an acceptable substitute, or do you think "the bot got this" should be part of the (permanent, and notification-generating) comment stream?

**Comment by badboy** [comment]
by CI status you mean one in the box that currently also holds the status about individual Travis status? 
Sure, that sounds even better.

**Comment by notriddle** [comment]
Yeah, that's what I mean.
