### ISSUE TITLE
Bors is dead right now :(

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#889]
bors r+ does not work, and dashbord does not function as well:

![image](https://user-images.githubusercontent.com/1711539/75338675-6a95ef00-588f-11ea-9016-f0361d2bb207.png)

**Comment by vext01** [comment]
Same here.

There's also a forum topic open:
https://forum.bors.tech/t/bors-is-stuck/445

**Comment by notriddle** [comment]
Uh, yeah. I found the cause.

Sorry about that.
