### ISSUE TITLE
use_codeowners doesn't support individual owners

### ISSUE THREAD

**Issue by cryslith** [bors-ng/bors-ng#936]
According to [GitHub's docs on CODEOWNERS](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners), a code owner can be either a team name or a username.  Bors doesn't support the latter.

**Comment by BuckyMaler** [comment]
@cryslith @notriddle this is a duplicate of #1127 and has been fixed, so this can be closed.
