### ISSUE TITLE
Public bors instance crashing?

### ISSUE THREAD

**Issue by vext01** [bors-ng/bors-ng#955]
Hi,

We are currently having problems with bors crashing on one of our PRs:
https://github.com/softdevteam/ykrustc/pull/102

It seems to have crashed in the past, but now only responds to pings.

I would have posted this on the forums, but they seem broken?
![image](https://user-images.githubusercontent.com/604955/81796263-b8b8a700-94fc-11ea-9547-fac7dc4e5271.png)

Thanks

**Comment by gebner** [comment]
This is because the PR is 1) from a fork, and 2) changes a file in `.github/workflows`.  See #806.

**Comment by vext01** [comment]
I see.

Github's documentation only covers adding the new permission for a user, whereas we need to add it for an organisation. I don't see any option to edit the permissions in that context.

![image](https://user-images.githubusercontent.com/604955/81798972-2e724200-9500-11ea-876c-e1c4d3c2a09a.png)

Any ideas?

**Comment by notriddle** [comment]
I've fixed the forum problem. The VM ran out of space.

**Comment by vext01** [comment]
> I've fixed the forum problem. The VM ran out of space.

Great, thanks.

I'm still stuck on how to add the permission to our organisation's Bors install. Any ideas? I fear I may need to reach out to github support.

**Comment by vext01** [comment]
@notriddle The new permission has been added to the bors app, right? Apparently we should get a notification and the ability to review the new permission.

**Comment by vext01** [comment]
I'm going to close this and take discussion to the forum.
