### ISSUE TITLE
Can't post on the forums

### ISSUE THREAD

**Issue by heinrich5991** [bors-ng/bors-ng#964]
I tried posting to https://forum.bors.tech/t/bors-responding-to-ping-but-not-try-or-r/476/5, but if I write my text and click "Reply" to confirm, it seems to work for a second, then an "Internal Server Error" message pops up and my post is greyed out (not seen when I reload the page).

I'm using Firefox 76.0.1.

> It does not seem to help. I also accepted the new permission on the https://github.com/ddnet/ddnet repository, but bors still hung on a batch containing a pull request that modified a Github actions script.
>
> It would be nice if bors could treat that as a failure for one specific pull request from the batch, retrying other as if the tests failed. Currently, the situation isn't documented well: You only see that bors says that the pull request is "Pending — Waiting in queue" (see e.g. https://github.com/ddnet/ddnet/pull/2188).

**Comment by notriddle** [comment]
I think I found the problem. Sorry about that; we were migrating to a newer version of PostgreSQL, and it kind of broke.
