### ISSUE TITLE
Can't update Bors-ng in Heroku

### ISSUE THREAD

**Issue by carlos-granados** [bors-ng/bors-ng#974]
We set up Bors-ng using the "Deploy to Heroku" button in your Github readme. It has been working great for some time but now we would like to update our Bors-ng version to the latest version. I tried the instructions I found here https://f-a.nz/dev/update-deploy-to-heroku-app/ 1 (basically download the Github repo, add a new Heroku remote and push master to this remote) but I got a "Push rejected" message (I guess that the master branch is somehow protected)

**Comment by notriddle** [comment]
It might've been because of the broken NPM dependencies. If it still doesn't work, try clearing the [heroku build cache](https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache).

**Comment by carlos-granados** [comment]
That (clearing the build cache) fixed the problem. Thanks!
