### ISSUE TITLE
Latest Bors-ng does not update statuses when CircleCI statuses update

### ISSUE THREAD

**Issue by carlos-granados** [bors-ng/bors-ng#975]
We have been using bors-ng since August 2018 but had not updated the version until very recently

We use CircleCI as our CI tool and there are 5 CircleCI jobs in our workflow that need to pass before we consider the build successful. These are defined in the bors.toml file:

```
status = [
"ci/circleci: phpunit",
"ci/circleci: jest",
"ci/circleci: code_quality",
"ci/circleci: behat",
"ci/circleci: cypress"
]
```

The problem is that even those jobs finish correctly in CircleCI, bors-ng does not seem to notice this. It updates some statuses, but not all, for example this is what I am seeing for a recent batch:

```
Status: ci/circleci: phpunit (Running) ci/circleci: code_quality (Running) ci/circleci: behat (Running) ci/circleci: jest (Running) ci/circleci: cypress (Succeeded)
```

(the statuses that show as succeeded and still running seem to vary randomly for every batch)

But at that point in time all jobs had finished correctly and were showing as passing in both CircleCI and Github. Bors-ng does not notice this and will eventually time out

This used to work perfectly until we updated to the latest master. No idea when this problem was introduced between August 2018 and now

**Comment by carlos-granados** [comment]
By slowly resetting our version of code I can say that the problem was introduced between merge #839 and merge #918. By looking at the changes between both versions I would say that the problem was introduced with merge #918 (branch `force-retry-status` ) as that is the only change in this period affecting statuses

**Comment by carlos-granados** [comment]
I can confirm that this was caused by merge #918 of the branch `force-retry-status` by @notriddle, reverting that change fixes the issue for us

**Comment by notriddle** [comment]
That pull request should only affect outgoing statuses, not incoming ones.

The problem it causes is probably related to the sleeping. If it makes responses take too long, it might be causing timeouts. So I've made a new version with a much shorter sleep gap. Can you try running with the [`timeout-hack-lower`](https://github.com/bors-ng/bors-ng/pull/976) branch?

**Comment by carlos-granados** [comment]
@notriddle by deploying your changes I was able to get it to work as well as when I completely removed the change. But this (either completely removing the change or modifying to a shorter sleep) does not seem to fully fix the problem, it just alleviates it. I am still seeing the problem happen. The difference is that before I was seeing this in every merge and now I only see it every 3-4 merges, so there must be some underlying change that causes this :-(

**Comment by carlos-granados** [comment]
Further testing shows that a shorter sleep does not really remove the problem it only makes it a little better, but worse than when the code is completely removed. These are my stats:

- With #918 applied: fails almost every merge (but not all)
- With #918 applied but a shorter sleep time: fails every 2-3 merges
- With #918 completely removed: fails every 4-5 merges

One thing to notice in case it helps: when things don't work there are no links in the status row in the batch status page, for example:

Status: [ci/circleci: phpunit (Succeeded)](https://circleci.com/gh/i6systems/in2plane-cloud/175209?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) [ci/circleci: code_quality (Running)](https://circleci.com/gh/i6systems/in2plane-cloud/175210?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) ci/circleci: behat (Running) ci/circleci: cypress (Running) [ci/circleci: jest (Succeeded)](https://circleci.com/gh/i6systems/in2plane-cloud/175211?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

Notice that the behat and cypress runners don't have a link and they will not get updated once they finish

**Comment by notriddle** [comment]
Are there any error messages in the dashboard logs area?

**Comment by carlos-granados** [comment]
No errors in the logs

**Comment by carlos-granados** [comment]
I finally got to the bottom of this: the root problem was introduced in February when Bors-ng was updated to use SSL by default. When we originally defined the configuration in Github we used http URLs for the config. This meant that when Github was accessing the `/webhook/github` endpoint, bors-ng was performing a redirection to the https counterpart. In the cases where the update of the status was failing I could see in the bors-ng logs that this redirect resulted in a 503 error with the message "Server Request Interrupted". Changing the urls in the Github config to use https has fixed the problem and now we are correctly receiving all the statuses.

The changes in #918 did not actually cause the problem but somehow made it more evident.

In my opinion, next actions should be:
- Use the shorter sleep time as this seems to help
- Investigate why the SSL redirection causes the 503 error and see if there is a way of fixing it
- If there is no fix, add a note in the documentation that you need to either use https URLs or disable the redirect to https by disabling using SSL by default
