### ISSUE TITLE
When adding PR description to the merge comment, escape @mentions

### ISSUE THREAD

**Issue by matklad** [bors-ng/bors-ng#984]
Github sends a notification if you are @mentioned in a commit message. This is unfortunate, because you'll get repeated notifications when the commit is rebased (or when you try several merges). Arguably, this is a bug in GitHub, but it seems like it's easier to fix this on bors' side, by escaping all `@mention`s

**Comment by matklad** [comment]
cc https://github.com/rust-analyzer/rust-analyzer/pull/5235

**Comment by notriddle** [comment]
This problem can be solved by adding a regex replacement to the [commit body generating algorithm](https://github.com/bors-ng/bors-ng/blob/f9dce726588bcb640bd8f876da12c71646b06bf4/lib/worker/batcher/message.ex#L143-L196). Most likely with a regex replacement line.

**Comment by jonas-schievink** [comment]
There's currently a GitHub bug that will resend these notifications even without the commit getting rebased, so the notification spam from this has gotten significantly worse over the last weeks

![screenshot-2021-04-12-15:47:34](https://user-images.githubusercontent.com/1786438/114405016-8ac56200-9ba6-11eb-86c9-81e46ac525ed.png)
